
import { Product, Seller, Category, Language, ShopProfile, ShopItem } from './types';

export const COLORS = {
  primary: '#2D5A27', // Forest Green
  secondary: '#6B4423', // Earth Brown
  accent: '#F97316', // Vibrant Orange
  background: '#F9FBF9',
};

export const SELLERS: Seller[] = [
  {
    id: 's1', name: 'Ramachandra Nursery', rating: 4.8, isVerified: true,
    distance: '4.2 km', phone: '+919876543210', location: 'Near Old Toll Gate, Pune',
    speciality: ['Saplings', 'Grafting', 'Fruit Trees'],
    daysOnApp: 312, totalSold: 4800,
    bio: 'Third-generation nursery specialising in grafted saplings and fruit trees. All plants are certified disease-free.',
    bioMr: 'तीन पिढ्यांचे नर्सरी, कलमे आणि फळझाडांमध्ये विशेष. सर्व रोपे रोगमुक्त प्रमाणित.',
    avatarColor: '#1A4D1A',
  },
  {
    id: 's2', name: 'Krishi Seva Center', rating: 4.5, isVerified: true,
    distance: '8.5 km', phone: '+919876543211', location: 'Main Market, Baramati',
    speciality: ['Seeds', 'Fertilizers', 'Agri Inputs'],
    daysOnApp: 198, totalSold: 2300,
    bio: 'Your one-stop agri-input center in Baramati. Government-empanelled distributor for premium seed brands.',
    bioMr: 'बारामतीमधील तुमचे संपूर्ण कृषी निविष्ठा केंद्र. सरकार मान्यताप्राप्त वितरक.',
    avatarColor: '#1A3D4D',
  },
  {
    id: 's3', name: 'Gajanan Seeds', rating: 3.9, isVerified: false,
    distance: '12.0 km', phone: '+919876543212', location: 'Satara Road',
    speciality: ['Seeds', 'Grains'],
    daysOnApp: 87, totalSold: 540,
    bio: 'Local seed trader with 10+ years of experience in Kharif and Rabi crop varieties.',
    bioMr: 'खरीप आणि रब्बी पिकांच्या जातींमध्ये १०+ वर्षांचा अनुभव असलेला स्थानिक बियाणे व्यापारी.',
    avatarColor: '#4D3A1A',
  },
  {
    id: 's4', name: 'Vitthal Agro Inputs', rating: 4.6, isVerified: true,
    distance: '6.8 km', phone: '+919876543213', location: 'APMC Yard, Solapur',
    speciality: ['Fertilizers', 'Drip Irrigation', 'Tools'],
    daysOnApp: 445, totalSold: 6200,
    bio: 'Solapur\'s leading agro input supplier. Authorized dealer for drip irrigation systems. Subsidy processing support available.',
    bioMr: 'सोलापूरचे अग्रगण्य कृषी निविष्ठा पुरवठादार. ठिबक सिंचन प्रणालीचे अधिकृत डीलर.',
    avatarColor: '#4D1A1A',
  },
  {
    id: 's5', name: 'Sahyadri Farm Fresh', rating: 4.3, isVerified: true,
    distance: '15.2 km', phone: '+919876543214', location: 'Nashik–Pune Highway, Igatpuri',
    speciality: ['Vegetables', 'Onion', 'Export Quality'],
    daysOnApp: 267, totalSold: 3900,
    bio: 'Farm-to-market fresh produce from the Sahyadri belt. Export-grade grading and packing available.',
    bioMr: 'सह्याद्री पट्ट्यातून थेट शेतातून बाजारात. निर्यात दर्जाचे ग्रेडिंग आणि पॅकिंग उपलब्ध.',
    avatarColor: '#1A4D3A',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sugarcane Saplings',
    nameMr: 'उसाची रोपे',
    category: 'Saplings',
    variety: 'CO 86032',
    varietyMr: 'सीओ ८६०३२',
    price: 3.5,
    unit: 'sapling',
    unitMr: 'रोप',
    quantity: 5000,
    age: '45 days',
    ageMr: '४५ दिवस',
    imageUrl: '/images/sugarcane-saplings.webp',
    sellerId: 's1',
    harvestDate: '2024-05-15',
    description: 'High-yield variety, disease resistant, and ready for planting. Grown under controlled environment.',
    descriptionMr: 'जास्त उत्पन्न देणारी जात, रोगप्रतिकारक आणि लागवडीसाठी तयार. नियंत्रित वातावरणात वाढवलेले.',
    mspPrice: 3.0,
  },
  {
    id: 'p2',
    name: 'Hybrid Tomato Seeds',
    nameMr: 'हायब्रीड टोमॅटो बियाणे',
    category: 'Seeds',
    variety: 'Abhinav',
    varietyMr: 'अभिनव',
    price: 450,
    unit: 'pack (50g)',
    unitMr: 'पॅक (५० ग्रॅम)',
    quantity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=800&auto=format&fit=crop',
    sellerId: 's2',
    description: 'F1 Hybrid Tomato seeds with excellent shelf life and firm fruit texture.',
    descriptionMr: 'उत्कृष्ट शेल्फ लाइफ आणि टणक फळांचा पोत असलेले F1 हायब्रीड टोमॅटो बियाणे.',
    mspPrice: 500,
  },
  {
    id: 'p3',
    name: 'NPK 19-19-19 Fertilizer',
    nameMr: 'NPK १९-१९-१९ खत',
    category: 'Fertilizer',
    variety: 'Water Soluble',
    varietyMr: 'पाण्यात विरघळणारे',
    price: 120,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 500,
    imageUrl: '/images/npk-19-19-19.webp',
    sellerId: 's2',
    description: 'Premium quality balanced NPK fertilizer for all crops.',
    descriptionMr: 'सर्व पिकांसाठी प्रीमियम दर्जाचे संतुलित NPK खत.',
  },
  {
    id: 'p5',
    name: 'Soybean (JS 335)',
    nameMr: 'सोयाबीन (जेएस ३३५)',
    category: 'Seeds',
    variety: 'JS 335',
    varietyMr: 'जेएस ३३५',
    price: 85,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 800,
    imageUrl: '/images/soybean.webp',
    sellerId: 's4',
    harvestDate: '2025-10-20',
    description: 'High-germination JS 335 soybean seeds. Drought-tolerant, ideal for Vidarbha and Marathwada regions.',
    descriptionMr: 'जास्त उगवण शक्तीचे जेएस ३३५ सोयाबीन बियाणे. दुष्काळ-सहिष्णु, विदर्भ आणि मराठवाड्यासाठी आदर्श.',
    mspPrice: 80,
  },
  {
    id: 'p6',
    name: 'Onion (Nasik Red)',
    nameMr: 'कांदा (नाशिक लाल)',
    category: 'Vegetables',
    variety: 'Nasik Red',
    varietyMr: 'नाशिक लाल',
    price: 32,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?q=80&w=800&auto=format&fit=crop',
    sellerId: 's5',
    harvestDate: '2025-04-01',
    description: 'Premium Nasik Red onions. Low moisture content, long shelf life, export-quality grading.',
    descriptionMr: 'उत्कृष्ट नाशिक लाल कांदे. कमी आर्द्रता, दीर्घ साठवण क्षमता, निर्यात दर्जाचे ग्रेडिंग.',
    mspPrice: 28,
  },
  {
    id: 'p7',
    name: 'Drip Irrigation Kit',
    nameMr: 'ठिबक सिंचन संच',
    category: 'Tools',
    variety: '2-Acre Set',
    varietyMr: '२ एकर संच',
    price: 12500,
    unit: 'set',
    unitMr: 'संच',
    quantity: 15,
    imageUrl: '/images/drip_irrigation_kit.jpg',
    sellerId: 's4',
    description: 'Complete drip irrigation kit for 2 acres. Includes inline drippers, mainline pipe, header pipe, and fittings. Subsidy eligible.',
    descriptionMr: '२ एकरसाठी संपूर्ण ठिबक सिंचन संच. इनलाइन ड्रिपर्स, मुख्य पाइप, हेडर पाइप आणि फिटिंगसह. अनुदानासाठी पात्र.',
    mspPrice: 12000,
  },
  {
    id: 'p4',
    name: 'Mango Graft (Kesar)',
    nameMr: 'केसर आंब्याची कलमे',
    category: 'Saplings',
    variety: 'Kesar',
    varietyMr: 'केसर',
    price: 180,
    unit: 'plant',
    unitMr: 'कलम',
    quantity: 250,
    age: '1 year',
    ageMr: '१ वर्ष',
    imageUrl: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?q=80&w=800&auto=format&fit=crop',
    sellerId: 's1',
    description: 'Healthy 1-year-old Kesar mango grafts. Guaranteed survival rate.',
    descriptionMr: 'निरोगी १ वर्ष जुन्या केसर आंब्याची कलमे. जगण्याची खात्रीशीर टक्केवारी.',
    mspPrice: 150,
  },
];

export const CATEGORIES: Category[] = [
  { id: 'c1', name: 'Seeds', nameMr: 'बियाणे', icon: '🌱' },
  { id: 'c2', name: 'Saplings', nameMr: 'रोपे', icon: '🌳' },
  { id: 'c3', name: 'Fertilizer', nameMr: 'खते', icon: '🧴' },
  { id: 'c4', name: 'Pesticides', nameMr: 'कीटकनाशके', icon: '🧪' },
  { id: 'c5', name: 'Tools', nameMr: 'अवजारे', icon: '🛠️' },
];

export const TRANSLATIONS = {
  en: {
    home: 'Market',
    sell: 'Sell',
    listings: 'Listings',
    myShop: 'My Listings',
    orders: 'Orders',
    profile: 'Profile',
    searchPlaceholder: 'Search seeds, saplings...',
    nearYou: 'Available Near You',
    trusted: 'Trusted Sellers',
    viewDetails: 'View Details',
    call: 'Call Seller',
    chat: 'Chat on App',
    transport: 'Need Transport?',
    addInventory: 'Sell Your Stock',
    publish: 'Publish Listing',
    variety: 'Variety',
    quantity: 'Quantity',
    price: 'Price',
    age: 'Age',
    location: 'Current Location',
    noOrders: 'No Orders Yet',
    noOrdersDesc: 'Your recent purchases and sales will appear here.',
    startShopping: 'Browse Market',
    unitsLabel: 'UNITS',
    verifiedChoice: 'Verified Choice',
    itemDetails: 'Item Details',
    qualityVerified: 'Quality Verified',
    selfPickup: 'Self-Pickup',
    requestTransport: 'Request Transport Help',
    messages: 'Messages',
    sendEnquiry: 'Send Enquiry',
    enquirySent: 'Enquiry Sent!',
    listingLocation: 'Listing Location',
    viewMap: 'View Map',
    comingSoon: 'Coming Soon',
    comingSoonDesc: 'Transport booking will be available soon. We\'ll notify you!',
    sellerProfile: 'Seller Profile',
    daysOnApp: 'Days on App',
    itemsSold: 'Items Sold',
    otherListings: 'Other Listings',
    contactSeller: 'Contact Seller',
    noMessages: 'No Messages Yet',
    noMessagesDesc: 'Send an enquiry on any listing to start a conversation.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `Hi, I'm interested in your ${productName} listed at ₹${price}/${unit} on Swaseva. Please share more details.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `नमस्कार, मला Swaseva वर तुमचे ${productName} (₹${price}/${unit}) पाहिले. कृपया अधिक माहिती द्या.`,
    cancel: 'Cancel', apply: 'Apply', reset: 'Reset', loading: 'Loading…',
    newsImpact: 'News & Our Impact', newsDesc: 'Farm news, MSP updates & more',
    nearbyShops: 'Nearby Dukaandaars', seeAll: 'See all →', freshListings: 'Fresh Listings',
    allIndia: 'All India', all: 'All', agriInputs: 'Agri Inputs',
    noProducts: 'No products found', fromOtherAreas: 'From other areas',
    compareCount: (n: number) => `Compare ${n}`,
    filterSort: 'Filter & Sort', sortBy: 'Sort By', newest: 'Newest',
    priceLow: 'Price: Low', priceHigh: 'Price: High', priceRange: 'Price Range (₹)',
    min: 'Min', max: 'Max',
    farmLocation: 'Farm Location', tapMapDrag: 'Tap on map or drag the pin',
    gettingAddress: 'Getting address…', tapMapSelect: 'Tap map to select',
    confirmLocation: 'Confirm Location', published: 'Published!', newListing: 'New Listing',
    stepOf: (n: number) => `Step ${n} of 3`,
    chooseCategory: 'Choose a Category', photosVideos: 'Photos / Videos', addMore: 'Add More',
    priceUnit: 'Price Unit', stockQty: 'Available Stock Quantity', stockUnit: 'Stock Unit',
    productLocation: 'Product Location', pickLocation: 'Pick location on map',
    mobileNumber: 'Mobile Number', nextStep: 'Next Step', trustBadge: 'Trust Badge',
    identityUploaded: 'Identity uploaded', verifiedBadgeWill: 'Verified Seller badge will be applied',
    uploadIdentity: 'Upload Identity', description: 'Description',
    descriptionHint: 'Tell buyers about quality and source...',
    newBtn: 'New', active: 'Active', views: 'Views', leads: 'Leads',
    activeListings: (n: number) => `${n} active listing${n !== 1 ? 's' : ''}`,
    dukaanPortal: 'Dukaan Portal', manageShop: 'Manage orders, inventory & sales',
    noListings: 'No listings in this category', sold: 'Sold', avail: 'avail.',
    editListing: 'Edit Listing', preview: 'Preview', delete: 'Delete',
    deleteConfirm: 'Delete this listing?', undo: 'Undo', listingDeleted: 'Listing deleted',
    becomeDukandaar: 'Become a Dukandaar', becomeShopkeeper: 'Become a Shopkeeper →',
    buyerEnquiries: 'Buyer Enquiries', reply: 'Reply', edit: 'Edit', availableQty: 'Available',
    accountSettings: 'Account Settings', personalInfo: 'Personal Info', fullName: 'Full name',
    languageLabel: 'Language', changePassword: 'Change Password',
    currentPwd: 'Current password', newPwd: 'New password',
    minChars: 'Minimum 8 characters required', saved: 'Saved!', saveChanges: 'Save Changes',
    notifications: 'Notifications', alerts: 'Alerts', channels: 'Channels',
    aadhaarCard: 'Aadhaar Card', identityVerification: 'Identity Verification',
    panCard: 'PAN Card', taxId: 'Tax Identification', bankAccount: 'Bank Account',
    linkPayments: 'Link for Payments', accountNumber: 'Account Number', ifscCode: 'IFSC Code',
    linkAccount: 'Link Account', farmDetails: 'Farm Details', farmerIdentity: 'Farmer Identity',
    landArea: 'Land area (acres)', satbaraNumber: '7/12 Satbara number',
    uploadSatbara: 'Upload 7/12 photo', submitReview: 'Submit for Review',
    kycVerification: 'KYC Verification', completion: 'Completion',
    complete: '✓ Complete', locked: '🔒 Locked',
    helpSupport: 'Help & Support', rateApp: 'Rate the App',
    rateDesc: 'Your feedback helps us improve', faq: 'Frequently Asked Questions',
    callUs: 'Call Us', chatNow: 'Chat now', emailUs: 'Email Us',
    shopRegistration: 'Shop Registration', premiumFarmer: 'Premium Farmer', myDukaan: 'My Dukaan',
    signOut: 'Sign Out', signOutConfirm: 'Sign out?', signOutDesc: 'You will need to log in again',
    verifiedStatus: 'Verified · 12 Jan 2025',
    listingsLabel: 'Listings', ratingLabel: 'Rating', salesLabel: 'Sales',
    totalAmount: 'Total Amount', tracking: 'Tracking',
    sellerLabel: 'Seller', buyerLabel: 'Buyer', priceBreakdown: 'Price Breakdown',
    itemTotal: 'Item Total', transportCost: 'Transport', paymentLabel: 'Payment',
    grandTotal: 'Grand Total', swaSevaProtected: 'Swaseva Protected',
    myTransactions: 'My Transactions', purchased: '🛒 Purchased', soldTab: '🌾 Sold',
    ordersLabel: 'Orders', spent: 'Spent', earned: 'Earned',
    swasevaLogistics: 'Swaseva Logistics',
  },
  mr: {
    home: 'बाजार',
    sell: 'विका',
    listings: 'लिस्टिंग',
    myShop: 'माझी यादी',
    orders: 'ऑर्डर्स',
    profile: 'प्रोफाईल',
    searchPlaceholder: 'बियाणे, रोपे शोधा...',
    nearYou: 'तुमच्या जवळ उपलब्ध',
    trusted: 'विश्वासार्ह विक्रेते',
    viewDetails: 'माहिती पहा',
    call: 'संपर्क करा',
    chat: 'चॅट करा',
    transport: 'वाहतूक हवी आहे?',
    addInventory: 'माल विका',
    publish: 'प्रकाशित करा',
    variety: 'वाण / जात',
    quantity: 'प्रमाण',
    price: 'किंमत',
    age: 'कालावधी',
    location: 'सध्याचे ठिकाण',
    noOrders: 'अद्याप ऑर्डर्स नाहीत',
    noOrdersDesc: 'तुमच्या अलीकडील खरेदी आणि विक्री येथे दिसतील.',
    startShopping: 'बाजार पहा',
    unitsLabel: 'नग/प्रमाण',
    verifiedChoice: 'सत्यापित निवड',
    itemDetails: 'वस्तूचा तपशील',
    qualityVerified: 'गुणवत्ता सत्यापित',
    selfPickup: 'स्वतः उचलणे',
    requestTransport: 'वाहतुकीसाठी मदत मागा',
    messages: 'संदेश',
    sendEnquiry: 'चौकशी पाठवा',
    enquirySent: 'चौकशी पाठवली!',
    listingLocation: 'लिस्टिंग ठिकाण',
    viewMap: 'नकाशा पहा',
    comingSoon: 'लवकरच येत आहे',
    comingSoonDesc: 'वाहतूक बुकिंग लवकरच उपलब्ध होईल. आम्ही तुम्हाला सूचित करू!',
    sellerProfile: 'विक्रेता प्रोफाईल',
    daysOnApp: 'App वर दिवस',
    itemsSold: 'विकलेल्या वस्तू',
    otherListings: 'इतर लिस्टिंग',
    contactSeller: 'विक्रेत्याशी संपर्क',
    noMessages: 'अद्याप संदेश नाहीत',
    noMessagesDesc: 'संभाषण सुरू करण्यासाठी कोणत्याही लिस्टिंगवर चौकशी पाठवा.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `नमस्कार, मला Swaseva वर तुमचे ${productName} (₹${price}/${unit}) पाहिले. कृपया अधिक माहिती द्या.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `नमस्कार, मला Swaseva वर तुमचे ${productName} (₹${price}/${unit}) पाहिले. कृपया अधिक माहिती द्या.`,
    cancel: 'रद्द', apply: 'लागू करा', reset: 'रीसेट', loading: 'लोड...',
    newsImpact: 'बातम्या आणि आमचा प्रभाव', newsDesc: 'शेती बातम्या, MSP अपडेट आणि अधिक',
    nearbyShops: 'जवळचे दुकानदार', seeAll: 'सर्व पहा →', freshListings: 'ताजे उत्पादन',
    allIndia: 'सर्व भारत', all: 'सर्व', agriInputs: 'कृषी निविष्ठा',
    noProducts: 'कोणतेही उत्पादन सापडले नाही', fromOtherAreas: 'इतर ठिकाणांहून',
    compareCount: (n: number) => `${n} तुलना करा`,
    filterSort: 'फिल्टर करा', sortBy: 'क्रमवारी', newest: 'नवीन',
    priceLow: 'कमी किंमत', priceHigh: 'जास्त किंमत', priceRange: 'किंमत मर्यादा (₹)',
    min: 'किमान', max: 'कमाल',
    farmLocation: 'शेताचे ठिकाण', tapMapDrag: 'नकाशावर टॅप करा किंवा मार्कर ड्रॅग करा',
    gettingAddress: 'ठिकाण शोधत आहे...', tapMapSelect: 'नकाशावर टॅप करा',
    confirmLocation: 'ठीक आहे', published: 'प्रकाशित झाले!', newListing: 'नवीन लिस्टिंग',
    stepOf: (n: number) => `पायरी ${n} / 3`,
    chooseCategory: 'श्रेणी निवडा', photosVideos: 'फोटो / व्हिडिओ', addMore: 'आणखी जोडा',
    priceUnit: 'किंमत एकक', stockQty: 'उपलब्ध साठा प्रमाण', stockUnit: 'साठा एकक',
    productLocation: 'उत्पादन ठिकाण', pickLocation: 'नकाशावर टॅप करा',
    mobileNumber: 'मोबाईल नंबर', nextStep: 'पुढे', trustBadge: 'विश्वास बॅज',
    identityUploaded: 'ओळखपत्र अपलोड झाले', verifiedBadgeWill: 'तुम्हाला Verified Seller बॅज मिळेल',
    uploadIdentity: 'ओळखपत्र अपलोड करा', description: 'वर्णन', descriptionHint: 'गुणवत्ता सांगा...',
    newBtn: 'नवीन', active: 'सक्रिय', views: 'व्ह्यूज', leads: 'चौकशी',
    activeListings: (n: number) => `${n} सक्रिय लिस्टिंग`,
    dukaanPortal: 'दुकान पोर्टल', manageShop: 'ऑर्डर, इन्व्हेंटरी आणि विक्री व्यवस्थापित करा',
    noListings: 'या श्रेणीत लिस्टिंग नाही', sold: 'विकले', avail: 'उपलब्ध',
    editListing: 'संपादित करा', preview: 'पूर्वावलोकन', delete: 'हटवा',
    deleteConfirm: 'लिस्टिंग हटवायची का?', undo: 'पूर्ववत करा', listingDeleted: 'लिस्टिंग हटवली',
    becomeDukandaar: 'दुकानदार म्हणून नोंदणी करा', becomeShopkeeper: 'दुकानदार व्हा →',
    buyerEnquiries: 'खरेदीची विचारणा', reply: 'उत्तर द्या', edit: 'संपादित करा', availableQty: 'मात्रा',
    accountSettings: 'खाते सेटिंग्ज', personalInfo: 'वैयक्तिक माहिती', fullName: 'पूर्ण नाव',
    languageLabel: 'भाषा', changePassword: 'पासवर्ड बदला',
    currentPwd: 'जुना पासवर्ड', newPwd: 'नवीन पासवर्ड',
    minChars: 'किमान 8 अक्षरे आवश्यक', saved: 'जतन झाले!', saveChanges: 'बदल जतन करा',
    notifications: 'सूचना', alerts: 'अलर्ट', channels: 'चॅनेल',
    aadhaarCard: 'आधार कार्ड', identityVerification: 'ओळख पडताळणी',
    panCard: 'PAN कार्ड', taxId: 'कर ओळख', bankAccount: 'बँक खाते',
    linkPayments: 'पेमेंट लिंक करा', accountNumber: 'खाते क्रमांक', ifscCode: 'IFSC कोड',
    linkAccount: 'खाते लिंक करा', farmDetails: 'शेत तपशील', farmerIdentity: 'शेतकरी ओळख',
    landArea: 'जमिनीचे क्षेत्रफळ (एकर)', satbaraNumber: '7/12 उतारा क्रमांक',
    uploadSatbara: '7/12 छायाचित्र अपलोड करा', submitReview: 'सबमिट करा',
    kycVerification: 'KYC पडताळणी', completion: 'पूर्णता',
    complete: '✓ पूर्ण', locked: '🔒 लॉक',
    helpSupport: 'मदत आणि सहाय्य', rateApp: 'अ‍ॅपला रेट करा',
    rateDesc: 'तुमचा अभिप्राय आम्हाला सुधारतो', faq: 'वारंवार विचारले जाणारे प्रश्न',
    callUs: 'फोन करा', chatNow: 'चॅट करा', emailUs: 'ईमेल करा',
    shopRegistration: 'दुकान नोंदणी', premiumFarmer: 'प्रीमियम शेतकरी', myDukaan: 'माझी दुकान',
    signOut: 'बाहेर पडा', signOutConfirm: 'लॉग आउट करायचे?', signOutDesc: 'तुम्हाला पुन्हा लॉग इन करावे लागेल',
    verifiedStatus: 'पडताळणी झाली · 12 जाने 2025',
    listingsLabel: 'लिस्टिंग', ratingLabel: 'रेटिंग', salesLabel: 'विक्री',
    totalAmount: 'एकूण रक्कम', tracking: 'ट्रॅकिंग',
    sellerLabel: 'विक्रेता', buyerLabel: 'खरेदीदार', priceBreakdown: 'किंमत तपशील',
    itemTotal: 'वस्तूची किंमत', transportCost: 'वाहतूक खर्च', paymentLabel: 'पेमेंट पद्धत',
    grandTotal: 'एकूण', swaSevaProtected: 'Swaseva संरक्षित',
    myTransactions: 'माझे व्यवहार', purchased: '🛒 खरेदी केले', soldTab: '🌾 विकले',
    ordersLabel: 'एकूण', spent: 'खर्च', earned: 'कमाई',
    swasevaLogistics: 'Swaseva लॉजिस्टिक्स',
  },
  hi: {
    home: 'बाज़ार',
    sell: 'माल बेचें',
    listings: 'लिस्टिंग',
    myShop: 'मेरी यादी',
    orders: 'ऑर्डर',
    profile: 'प्रोफ़ाइल',
    searchPlaceholder: 'बीज, पौधे खोजें...',
    nearYou: 'आपके पास उपलब्ध',
    trusted: 'भरोसेमंद विक्रेता',
    viewDetails: 'विवरण देखें',
    call: 'कॉल करें',
    chat: 'चैट करें',
    transport: 'परिवहन चाहिए?',
    addInventory: 'माल बेचें',
    publish: 'सूची करें',
    variety: 'किस्म',
    quantity: 'मात्रा',
    price: 'मूल्य',
    age: 'आयु',
    location: 'वर्तमान स्थान',
    noOrders: 'कोई ऑर्डर नहीं',
    noOrdersDesc: 'आपकी हालिया खरीद और बिक्री यहाँ दिखेगी।',
    startShopping: 'बाज़ार देखें',
    unitsLabel: 'नग',
    verifiedChoice: 'सत्यापित विकल्प',
    itemDetails: 'वस्तु का विवरण',
    qualityVerified: 'गुणवत्ता सत्यापित',
    selfPickup: 'खुद उठाएं',
    requestTransport: 'परिवहन सहायता मांगें',
    messages: 'संदेश',
    sendEnquiry: 'पूछताछ भेजें',
    enquirySent: 'पूछताछ भेजी!',
    listingLocation: 'स्थान',
    viewMap: 'नक्शा देखें',
    comingSoon: 'जल्द आ रहा है',
    comingSoonDesc: 'परिवहन बुकिंग जल्द उपलब्ध होगी। हम आपको सूचित करेंगे!',
    sellerProfile: 'विक्रेता प्रोफ़ाइल',
    daysOnApp: 'ऐप पर दिन',
    itemsSold: 'बिकी वस्तुएं',
    otherListings: 'अन्य सूचियां',
    contactSeller: 'विक्रेता से संपर्क',
    noMessages: 'कोई संदेश नहीं',
    noMessagesDesc: 'बातचीत शुरू करने के लिए कोई पूछताछ भेजें।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `नमस्ते, Swaseva पर आपका ${productName} (₹${price}/${unit}) देखा। कृपया अधिक जानकारी दें।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `नमस्ते, Swaseva पर आपका ${productName} (₹${price}/${unit}) देखा। कृपया अधिक जानकारी दें।`,
    cancel: 'रद्द करें', apply: 'लागू करें', reset: 'रीसेट', loading: 'लोड हो रहा है…',
    newsImpact: 'समाचार और हमारा प्रभाव', newsDesc: 'कृषि समाचार, MSP अपडेट और अधिक',
    nearbyShops: 'नज़दीकी दुकानदार', seeAll: 'सभी देखें →', freshListings: 'ताज़ी सूचियां',
    allIndia: 'सभी भारत', all: 'सभी', agriInputs: 'कृषि सामग्री',
    noProducts: 'कोई उत्पाद नहीं मिला', fromOtherAreas: 'अन्य क्षेत्रों से',
    compareCount: (n: number) => `${n} तुलना करें`,
    filterSort: 'फ़िल्टर करें', sortBy: 'क्रमबद्ध करें', newest: 'नवीनतम',
    priceLow: 'कम कीमत', priceHigh: 'ज़्यादा कीमत', priceRange: 'कीमत सीमा (₹)',
    min: 'न्यूनतम', max: 'अधिकतम',
    farmLocation: 'खेत का स्थान', tapMapDrag: 'नक्शे पर टैप करें या पिन खींचें',
    gettingAddress: 'पता मिल रहा है…', tapMapSelect: 'नक्शे पर टैप करें',
    confirmLocation: 'स्थान पक्का करें', published: 'प्रकाशित!', newListing: 'नई सूची',
    stepOf: (n: number) => `चरण ${n} / 3`,
    chooseCategory: 'श्रेणी चुनें', photosVideos: 'फ़ोटो / वीडियो', addMore: 'और जोड़ें',
    priceUnit: 'मूल्य इकाई', stockQty: 'उपलब्ध स्टॉक मात्रा', stockUnit: 'स्टॉक इकाई',
    productLocation: 'उत्पाद स्थान', pickLocation: 'नक्शे पर टैप करें',
    mobileNumber: 'मोबाइल नंबर', nextStep: 'आगे', trustBadge: 'विश्वास बैज',
    identityUploaded: 'पहचान अपलोड', verifiedBadgeWill: 'Verified Seller बैज मिलेगा',
    uploadIdentity: 'पहचान अपलोड करें', description: 'विवरण', descriptionHint: 'गुणवत्ता के बारे में बताएं...',
    newBtn: 'नई', active: 'सक्रिय', views: 'व्यूज़', leads: 'लीड्स',
    activeListings: (n: number) => `${n} सक्रिय सूची`,
    dukaanPortal: 'दुकान पोर्टल', manageShop: 'ऑर्डर, इन्वेंटरी और बिक्री',
    noListings: 'इस श्रेणी में कोई सूची नहीं', sold: 'बिका', avail: 'उपलब्ध',
    editListing: 'सूची संपादित', preview: 'पूर्वावलोकन', delete: 'हटाएं',
    deleteConfirm: 'यह सूची हटाएं?', undo: 'पूर्ववत', listingDeleted: 'सूची हटाई',
    becomeDukandaar: 'दुकानदार के रूप में पंजीकरण', becomeShopkeeper: 'दुकानदार बनें →',
    buyerEnquiries: 'खरीदार पूछताछ', reply: 'जवाब दें', edit: 'संपादित', availableQty: 'उपलब्ध',
    accountSettings: 'खाता सेटिंग', personalInfo: 'व्यक्तिगत जानकारी', fullName: 'पूरा नाम',
    languageLabel: 'भाषा', changePassword: 'पासवर्ड बदलें',
    currentPwd: 'वर्तमान पासवर्ड', newPwd: 'नया पासवर्ड',
    minChars: 'न्यूनतम 8 वर्ण आवश्यक', saved: 'सहेजा!', saveChanges: 'परिवर्तन सहेजें',
    notifications: 'सूचनाएं', alerts: 'अलर्ट', channels: 'चैनल',
    aadhaarCard: 'आधार कार्ड', identityVerification: 'पहचान सत्यापन',
    panCard: 'PAN कार्ड', taxId: 'कर पहचान', bankAccount: 'बैंक खाता',
    linkPayments: 'भुगतान लिंक', accountNumber: 'खाता नंबर', ifscCode: 'IFSC कोड',
    linkAccount: 'खाता लिंक', farmDetails: 'खेत विवरण', farmerIdentity: 'किसान पहचान',
    landArea: 'भूमि क्षेत्र (एकड़)', satbaraNumber: '7/12 सतबारा नंबर',
    uploadSatbara: '7/12 फ़ोटो', submitReview: 'समीक्षा जमा करें',
    kycVerification: 'KYC सत्यापन', completion: 'पूर्णता',
    complete: '✓ पूर्ण', locked: '🔒 लॉक',
    helpSupport: 'सहायता', rateApp: 'ऐप रेट करें',
    rateDesc: 'आपकी प्रतिक्रिया हमें बेहतर बनाती है', faq: 'अक्सर पूछे जाने वाले प्रश्न',
    callUs: 'कॉल करें', chatNow: 'चैट करें', emailUs: 'ईमेल करें',
    shopRegistration: 'दुकान पंजीकरण', premiumFarmer: 'प्रीमियम किसान', myDukaan: 'मेरी दुकान',
    signOut: 'साइन आउट', signOutConfirm: 'साइन आउट?', signOutDesc: 'फिर से लॉग इन करना होगा',
    verifiedStatus: 'सत्यापित · 12 जन 2025',
    listingsLabel: 'सूचियां', ratingLabel: 'रेटिंग', salesLabel: 'बिक्री',
    totalAmount: 'कुल राशि', tracking: 'ट्रैकिंग',
    sellerLabel: 'विक्रेता', buyerLabel: 'खरीदार', priceBreakdown: 'मूल्य विवरण',
    itemTotal: 'वस्तु मूल्य', transportCost: 'परिवहन', paymentLabel: 'भुगतान',
    grandTotal: 'कुल', swaSevaProtected: 'Swaseva संरक्षित',
    myTransactions: 'मेरे लेनदेन', purchased: '🛒 खरीदा', soldTab: '🌾 बेचा',
    ordersLabel: 'ऑर्डर', spent: 'खर्च', earned: 'कमाई',
    swasevaLogistics: 'Swaseva लॉजिस्टिक्स',
  },
  gu: {
    home: 'બજાર',
    sell: 'માલ વેચો',
    listings: 'લિસ્ટિંગ',
    myShop: 'મારી યાદી',
    orders: 'ઓર્ડર',
    profile: 'પ્રોફાઇલ',
    searchPlaceholder: 'બિયારણ, છોડ શોધો...',
    nearYou: 'તમારી નજીક ઉપલબ્ધ',
    trusted: 'વિશ્વસનીય વિક્રેતા',
    viewDetails: 'વિગત જુઓ',
    call: 'ફોન કરો',
    chat: 'ચેટ કરો',
    transport: 'વાહન જોઈએ?',
    addInventory: 'માલ વેચો',
    publish: 'પ્રકાશિત કરો',
    variety: 'જાત',
    quantity: 'જથ્થો',
    price: 'ભાવ',
    age: 'ઉંમર',
    location: 'વર્તમાન સ્થાન',
    noOrders: 'કોઈ ઓર્ડર નથી',
    noOrdersDesc: 'તમારી ખરીદી અને વેચાણ અહીં દેખાશે.',
    startShopping: 'બજાર જુઓ',
    unitsLabel: 'નંગ',
    verifiedChoice: 'ચકાસાયેલ પસંદગી',
    itemDetails: 'વસ્તુની વિગત',
    qualityVerified: 'ગુણવત્તા ચકાસાઈ',
    selfPickup: 'જાતે લઈ જાઓ',
    requestTransport: 'વાહન સહાય માગો',
    messages: 'સંદેશ',
    sendEnquiry: 'પૂછપરછ મોકલો',
    enquirySent: 'પૂછપરછ મોકલાઈ!',
    listingLocation: 'સ્થાન',
    viewMap: 'નકશો જુઓ',
    comingSoon: 'જલ્દ આવે છે',
    comingSoonDesc: 'વાહન બુકિંગ જલ્દ ઉપલબ્ધ થશે. અમે જાણ કરીશું!',
    sellerProfile: 'વિક્રેતા પ્રોફાઇલ',
    daysOnApp: 'App પર દિવસ',
    itemsSold: 'વેચાઈ ગઈ વસ્તુઓ',
    otherListings: 'અન્ય લિસ્ટિંગ',
    contactSeller: 'વિક્રેતા સાથે સંપર્ક',
    noMessages: 'કોઈ સંદેશ નથી',
    noMessagesDesc: 'વાર્તાલાપ શરૂ કરવા પૂછપરછ મોકલો.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `નમસ્તે, Swaseva પર તમારો ${productName} (₹${price}/${unit}) જોયો. વધુ માહિતી આપો.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `નમસ્તે, Swaseva પર તમારો ${productName} (₹${price}/${unit}) જોયો. વધુ માહિતી આપો.`,
    cancel: 'રદ્દ', apply: 'લાગુ', reset: 'રીસેટ', loading: 'લોડ…',
    newsImpact: 'સમાચાર અને અસર', newsDesc: 'ખેત સમાચાર, MSP અને વધુ',
    nearbyShops: 'નજીકના દુકાનદાર', seeAll: 'બધા →', freshListings: 'તાજી સૂચિ',
    allIndia: 'સમગ્ર ભારત', all: 'બધા', agriInputs: 'ખેત સામગ્રી',
    noProducts: 'કોઈ ઉત્પાદ નહીં', fromOtherAreas: 'અન્ય વિસ્તારોમાંથી',
    compareCount: (n: number) => `${n} સરખામણી`,
    filterSort: 'ફિલ્ટર', sortBy: 'ક્રમ', newest: 'નવીન',
    priceLow: 'ઓછો ભાવ', priceHigh: 'વધુ ભાવ', priceRange: 'ભાવ (₹)',
    min: 'ન્યૂ.', max: 'મહ.',
    farmLocation: 'ખેતની જગ્યા', tapMapDrag: 'નકશા પર ટૅપ કરો',
    gettingAddress: 'સરનામું…', tapMapSelect: 'નકશા પર ટૅપ',
    confirmLocation: 'સ્થાન પાક્કું', published: 'પ્રકાશિત!', newListing: 'નવી સૂચિ',
    stepOf: (n: number) => `પગલું ${n} / 3`,
    chooseCategory: 'શ્રેણી', photosVideos: 'ફોટો / વિડિઓ', addMore: 'વધુ',
    priceUnit: 'ભાવ એકમ', stockQty: 'સ્ટૉક', stockUnit: 'સ્ટૉક એકમ',
    productLocation: 'સ્થાન', pickLocation: 'નકશા પર ટૅપ',
    mobileNumber: 'મોબાઇલ', nextStep: 'આગળ', trustBadge: 'વિ. બૅજ',
    identityUploaded: 'ઓળખ અપ.', verifiedBadgeWill: 'Verified બૅજ મળશે',
    uploadIdentity: 'ઓળખ અપ.', description: 'વર્ણન', descriptionHint: 'ગુણવત્તા…',
    newBtn: 'નવો', active: 'સક્રિય', views: 'વ્યૂ', leads: 'લીડ',
    activeListings: (n: number) => `${n} સક્રિય`,
    dukaanPortal: 'દુકાન પોર્ટલ', manageShop: 'ઑર્ડર, ઇન્વ. અને વ.',
    noListings: 'સૂચિ નથી', sold: 'વેચ્યો', avail: 'ઉ.',
    editListing: 'સંપ.', preview: 'પૂ.', delete: 'કાઢો',
    deleteConfirm: 'સૂચિ કાઢવી?', undo: 'પૂ.', listingDeleted: 'સૂચિ કાઢી',
    becomeDukandaar: 'દુ. નોંધણી', becomeShopkeeper: 'દુ. બનો →',
    buyerEnquiries: 'ખ. પૂછ.', reply: 'જ.', edit: 'સ.', availableQty: 'ઉ.',
    accountSettings: 'ખા. સેટ.', personalInfo: 'માહિ.', fullName: 'નામ',
    languageLabel: 'ભાષા', changePassword: 'પાસ. બદ.',
    currentPwd: 'હ. પ.', newPwd: 'ન. પ.',
    minChars: 'ઓ. 8 અ.', saved: 'સ.!', saveChanges: 'સાચ.',
    notifications: 'સૂ.', alerts: 'ચ.', channels: 'ચ.',
    aadhaarCard: 'આધાર', identityVerification: 'ઓ. ચ.',
    panCard: 'PAN', taxId: 'કર', bankAccount: 'બૅ. ખ.',
    linkPayments: 'ચ. લ.', accountNumber: 'ખ. ન.', ifscCode: 'IFSC',
    linkAccount: 'ખ. લ.', farmDetails: 'ખ. વ.', farmerIdentity: 'ખ. ઓ.',
    landArea: 'જ. (એ.)', satbaraNumber: '7/12',
    uploadSatbara: '7/12 ફ.', submitReview: 'સ.',
    kycVerification: 'KYC', completion: 'પૂ.',
    complete: '✓ પૂ.', locked: '🔒 લ.',
    helpSupport: 'સ.', rateApp: 'ર.',
    rateDesc: 'અ.', faq: 'FAQ',
    callUs: 'ફ.', chatNow: 'ચ.', emailUs: 'ઈ.',
    shopRegistration: 'દ. ન.', premiumFarmer: 'પ્ર. ખ.', myDukaan: 'મ. દ.',
    signOut: 'સ. આ.', signOutConfirm: 'સ. આ.?', signOutDesc: 'ફ. લ. ક. પ.',
    verifiedStatus: 'ચ. · 12 જ. 2025',
    listingsLabel: 'સૂ.', ratingLabel: 'ર.', salesLabel: 'વ.',
    totalAmount: 'કુ.', tracking: 'ટ.',
    sellerLabel: 'વ.', buyerLabel: 'ખ.', priceBreakdown: 'ભ.',
    itemTotal: 'વ.', transportCost: 'વ.', paymentLabel: 'ચ.',
    grandTotal: 'કુ.', swaSevaProtected: 'Swaseva સ.',
    myTransactions: 'વ્ય.', purchased: '🛒 ખ.', soldTab: '🌾 વ.',
    ordersLabel: 'ઑ.', spent: 'ખ.', earned: 'ક.',
    swasevaLogistics: 'Swaseva લ.',
  },
  te: {
    home: 'మార్కెట్',
    sell: 'అమ్మండి',
    listings: 'జాబితాలు',
    myShop: 'నా జాబితా',
    orders: 'ఆర్డర్లు',
    profile: 'ప్రొఫైల్',
    searchPlaceholder: 'విత్తనాలు, మొక్కలు వెతకండి...',
    nearYou: 'మీ దగ్గర అందుబాటులో',
    trusted: 'నమ్మకమైన విక్రేతలు',
    viewDetails: 'వివరాలు చూడండి',
    call: 'కాల్ చేయండి',
    chat: 'చాట్ చేయండి',
    transport: 'రవాణా కావాలా?',
    addInventory: 'అమ్మండి',
    publish: 'ప్రచురించండి',
    variety: 'రకం',
    quantity: 'పరిమాణం',
    price: 'ధర',
    age: 'వయసు',
    location: 'ప్రస్తుత స్థానం',
    noOrders: 'ఆర్డర్లు లేవు',
    noOrdersDesc: 'మీ తాజా కొనుగోళ్లు మరియు అమ్మకాలు ఇక్కడ కనిపిస్తాయి.',
    startShopping: 'మార్కెట్ చూడండి',
    unitsLabel: 'నగ్',
    verifiedChoice: 'ధృవీకరించిన ఎంపిక',
    itemDetails: 'వస్తువు వివరాలు',
    qualityVerified: 'నాణ్యత ధృవీకరించబడింది',
    selfPickup: 'స్వయంగా తీసుకెళ్ళండి',
    requestTransport: 'రవాణా సహాయం కోరండి',
    messages: 'సందేశాలు',
    sendEnquiry: 'విచారణ పంపండి',
    enquirySent: 'విచారణ పంపబడింది!',
    listingLocation: 'స్థానం',
    viewMap: 'మ్యాప్ చూడండి',
    comingSoon: 'త్వరలో వస్తోంది',
    comingSoonDesc: 'రవాణా బుకింగ్ త్వరలో అందుబాటులో ఉంటుంది.',
    sellerProfile: 'విక్రేత ప్రొఫైల్',
    daysOnApp: 'యాప్‌లో రోజులు',
    itemsSold: 'అమ్మిన వస్తువులు',
    otherListings: 'ఇతర జాబితాలు',
    contactSeller: 'విక్రేతను సంప్రదించండి',
    noMessages: 'సందేశాలు లేవు',
    noMessagesDesc: 'సంభాషణ ప్రారంభించడానికి విచారణ పంపండి.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `నమస్కారం, Swaseva లో మీ ${productName} (₹${price}/${unit}) చూశాను. దయచేసి మరిన్ని వివరాలు పంపండి.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `నమస్కారం, Swaseva లో మీ ${productName} (₹${price}/${unit}) చూశాను. దయచేసి మరిన్ని వివరాలు పంపండి.`,
    cancel: 'రద్దు', apply: 'వర్తింపు', reset: 'రీసెట్', loading: 'లోడ్…',
    newsImpact: 'వార్తలు మరియు ప్రభావం', newsDesc: 'వ్యవసాయ వార్తలు, MSP నవీకరణలు',
    nearbyShops: 'దగ్గరి దుకాణాలు', seeAll: 'అన్నీ →', freshListings: 'తాజా జాబితాలు',
    allIndia: 'మొత్తం భారతం', all: 'అన్నీ', agriInputs: 'వ్యవసాయ సామగ్రి',
    noProducts: 'ఉత్పత్తులు లేవు', fromOtherAreas: 'ఇతర ప్రాంతాల నుండి',
    compareCount: (n: number) => `${n} పోల్చడం`,
    filterSort: 'ఫిల్టర్', sortBy: 'క్రమం', newest: 'కొత్తది',
    priceLow: 'తక్కువ ధర', priceHigh: 'అధిక ధర', priceRange: 'ధర పరిధి (₹)',
    min: 'కనిష్ట', max: 'గరిష్ట',
    farmLocation: 'పొలం స్థానం', tapMapDrag: 'మ్యాప్‌లో టాప్ చేయండి',
    gettingAddress: 'చిరునామా…', tapMapSelect: 'మ్యాప్‌లో టాప్',
    confirmLocation: 'స్థానం నిర్ధారించు', published: 'ప్రచురితం!', newListing: 'కొత్త జాబిత',
    stepOf: (n: number) => `దశ ${n} / 3`,
    chooseCategory: 'వర్గం', photosVideos: 'ఫొటో / వీడియో', addMore: 'మరిన్ని',
    priceUnit: 'ధర యూనిట్', stockQty: 'స్టాక్', stockUnit: 'స్టాక్ యూనిట్',
    productLocation: 'స్థానం', pickLocation: 'మ్యాప్‌లో టాప్',
    mobileNumber: 'మొబైల్', nextStep: 'తర్వాత', trustBadge: 'నమ్మకం బ్యాడ్జ్',
    identityUploaded: 'గుర్తింపు అప్.', verifiedBadgeWill: 'Verified బ్యాడ్జ్ వస్తుంది',
    uploadIdentity: 'గుర్తింపు అప్.', description: 'వివరణ', descriptionHint: 'నాణ్యత గురించి…',
    newBtn: 'కొత్తది', active: 'చురుకైన', views: 'వ్యూలు', leads: 'లీడ్స్',
    activeListings: (n: number) => `${n} చురుకైన జాబితాలు`,
    dukaanPortal: 'దుకాణ పోర్టల్', manageShop: 'ఆర్డర్లు, ఇన్వెంటరీ',
    noListings: 'జాబితాలు లేవు', sold: 'అమ్మారు', avail: 'అందు.',
    editListing: 'సవరించు', preview: 'ముందుచూపు', delete: 'తొలగించు',
    deleteConfirm: 'జాబిత తొలగించాలా?', undo: 'రద్దు', listingDeleted: 'జాబిత తొలగించబడింది',
    becomeDukandaar: 'దుకాణదారుగా నమోదు', becomeShopkeeper: 'దుకాణదారు అవ్వండి →',
    buyerEnquiries: 'కొనుగోలుదారు విచారణ', reply: 'జవాబు', edit: 'సవరించు', availableQty: 'అందు.',
    accountSettings: 'ఖాతా సెట్టింగ్స్', personalInfo: 'వ్యక్తిగత', fullName: 'పేరు',
    languageLabel: 'భాష', changePassword: 'పాస్‌వర్డ్ మార్చు',
    currentPwd: 'పాత పాస్.', newPwd: 'కొత్త పాస్.',
    minChars: 'కనీసం 8 అక్షరాలు', saved: 'సేవ్!', saveChanges: 'మార్పులు సేవ్',
    notifications: 'నోటిఫికేషన్లు', alerts: 'హెచ్చరికలు', channels: 'చానెల్లు',
    aadhaarCard: 'ఆధార్', identityVerification: 'గుర్తింపు',
    panCard: 'PAN', taxId: 'పన్ను గుర్తింపు', bankAccount: 'బ్యాంక్',
    linkPayments: 'చెల్లింపు లింక్', accountNumber: 'ఖాతా నెం.', ifscCode: 'IFSC',
    linkAccount: 'ఖాతా లింక్', farmDetails: 'పొలం వివరాలు', farmerIdentity: 'రైతు గుర్తింపు',
    landArea: 'భూమి (ఎకరాలు)', satbaraNumber: '7/12 నంబర్',
    uploadSatbara: '7/12 ఫొటో', submitReview: 'సమీక్ష',
    kycVerification: 'KYC', completion: 'పూర్తి',
    complete: '✓ పూర్తి', locked: '🔒 లాక్',
    helpSupport: 'సహాయం', rateApp: 'రేట్ చేయండి',
    rateDesc: 'మీ అభిప్రాయం', faq: 'FAQ',
    callUs: 'కాల్', chatNow: 'చాట్', emailUs: 'ఇమెయిల్',
    shopRegistration: 'దుకాణ నమోదు', premiumFarmer: 'ప్రీమియం రైతు', myDukaan: 'నా దుకాణం',
    signOut: 'సైన్ అవుట్', signOutConfirm: 'సైన్ అవుట్?', signOutDesc: 'మళ్ళీ లాగిన్ అవ్వాలి',
    verifiedStatus: 'వెరిఫైడ్ · 12 జన 2025',
    listingsLabel: 'జాబితాలు', ratingLabel: 'రేటింగ్', salesLabel: 'అమ్మకాలు',
    totalAmount: 'మొత్తం', tracking: 'ట్రాకింగ్',
    sellerLabel: 'విక్రేత', buyerLabel: 'కొనుగోలుదారు', priceBreakdown: 'ధర',
    itemTotal: 'వస్తువు', transportCost: 'రవాణా', paymentLabel: 'చెల్లింపు',
    grandTotal: 'మొత్తం', swaSevaProtected: 'Swaseva రక్షిత',
    myTransactions: 'నా లావాదేవీలు', purchased: '🛒 కొన్నది', soldTab: '🌾 అమ్మింది',
    ordersLabel: 'ఆర్డర్లు', spent: 'ఖర్చు', earned: 'సంపాదన',
    swasevaLogistics: 'Swaseva లాజిస్టిక్స్',
  },
  pa: {
    home: 'ਬਾਜ਼ਾਰ',
    sell: 'ਮਾਲ ਵੇਚੋ',
    listings: 'ਲਿਸਟਿੰਗ',
    myShop: 'ਮੇਰੀ ਸੂਚੀ',
    orders: 'ਆਰਡਰ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    searchPlaceholder: 'ਬੀਜ, ਬੂਟੇ ਲੱਭੋ...',
    nearYou: 'ਤੁਹਾਡੇ ਨੇੜੇ ਉਪਲਬਧ',
    trusted: 'ਭਰੋਸੇਯੋਗ ਵਿਕ੍ਰੇਤਾ',
    viewDetails: 'ਵੇਰਵਾ ਦੇਖੋ',
    call: 'ਕਾਲ ਕਰੋ',
    chat: 'ਚੈਟ ਕਰੋ',
    transport: 'ਆਵਾਜਾਈ ਚਾਹੀਦੀ ਹੈ?',
    addInventory: 'ਮਾਲ ਵੇਚੋ',
    publish: 'ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    variety: 'ਕਿਸਮ',
    quantity: 'ਮਾਤਰਾ',
    price: 'ਕੀਮਤ',
    age: 'ਉਮਰ',
    location: 'ਮੌਜੂਦਾ ਟਿਕਾਣਾ',
    noOrders: 'ਕੋਈ ਆਰਡਰ ਨਹੀਂ',
    noOrdersDesc: 'ਤੁਹਾਡੀਆਂ ਹਾਲੀਆ ਖਰੀਦਾਂ ਅਤੇ ਵਿਕਰੀ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।',
    startShopping: 'ਬਾਜ਼ਾਰ ਦੇਖੋ',
    unitsLabel: 'ਨੰਗ',
    verifiedChoice: 'ਪ੍ਰਮਾਣਿਤ ਵਿਕਲਪ',
    itemDetails: 'ਵਸਤੂ ਦਾ ਵੇਰਵਾ',
    qualityVerified: 'ਗੁਣਵੱਤਾ ਤਸਦੀਕ',
    selfPickup: 'ਖੁਦ ਲੈ ਜਾਓ',
    requestTransport: 'ਆਵਾਜਾਈ ਸਹਾਇਤਾ ਮੰਗੋ',
    messages: 'ਸੁਨੇਹੇ',
    sendEnquiry: 'ਪੁੱਛਗਿੱਛ ਭੇਜੋ',
    enquirySent: 'ਪੁੱਛਗਿੱਛ ਭੇਜੀ!',
    listingLocation: 'ਟਿਕਾਣਾ',
    viewMap: 'ਨਕਸ਼ਾ ਦੇਖੋ',
    comingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
    comingSoonDesc: 'ਟ੍ਰਾਂਸਪੋਰਟ ਬੁਕਿੰਗ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗੀ।',
    sellerProfile: 'ਵਿਕ੍ਰੇਤਾ ਪ੍ਰੋਫਾਈਲ',
    daysOnApp: 'App ਤੇ ਦਿਨ',
    itemsSold: 'ਵਿਕੀਆਂ ਵਸਤੂਆਂ',
    otherListings: 'ਹੋਰ ਲਿਸਟਿੰਗ',
    contactSeller: 'ਵਿਕ੍ਰੇਤਾ ਨਾਲ ਸੰਪਰਕ',
    noMessages: 'ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ',
    noMessagesDesc: 'ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਪੁੱਛਗਿੱਛ ਭੇਜੋ।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, Swaseva ਤੇ ਤੁਹਾਡਾ ${productName} (₹${price}/${unit}) ਦੇਖਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਜਾਣਕਾਰੀ ਦਿਓ।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, Swaseva ਤੇ ਤੁਹਾਡਾ ${productName} (₹${price}/${unit}) ਦੇਖਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਜਾਣਕਾਰੀ ਦਿਓ।`,
    cancel: 'ਰੱਦ', apply: 'ਲਾਗੂ', reset: 'ਰੀਸੈੱਟ', loading: 'ਲੋਡ…',
    newsImpact: 'ਖ਼ਬਰਾਂ ਅਤੇ ਪ੍ਰਭਾਵ', newsDesc: 'ਖੇਤੀ ਖ਼ਬਰਾਂ, MSP ਅਪਡੇਟ',
    nearbyShops: 'ਨੇੜੇ ਦੁਕਾਨਦਾਰ', seeAll: 'ਸਭ →', freshListings: 'ਤਾਜ਼ੀਆਂ ਸੂਚੀਆਂ',
    allIndia: 'ਸਾਰਾ ਭਾਰਤ', all: 'ਸਭ', agriInputs: 'ਖੇਤੀ ਸਮੱਗਰੀ',
    noProducts: 'ਕੋਈ ਉਤਪਾਦ ਨਹੀਂ', fromOtherAreas: 'ਹੋਰ ਖੇਤਰਾਂ ਤੋਂ',
    compareCount: (n: number) => `${n} ਤੁਲਨਾ`,
    filterSort: 'ਫਿਲਟਰ', sortBy: 'ਕ੍ਰਮ', newest: 'ਨਵੇਂ',
    priceLow: 'ਘੱਟ ਕੀਮਤ', priceHigh: 'ਵੱਧ ਕੀਮਤ', priceRange: 'ਕੀਮਤ (₹)',
    min: 'ਘੱਟੋ', max: 'ਵੱਧ',
    farmLocation: 'ਖੇਤ ਦੀ ਜਗ੍ਹਾ', tapMapDrag: 'ਨਕਸ਼ੇ ਤੇ ਟੈਪ ਕਰੋ',
    gettingAddress: 'ਪਤਾ…', tapMapSelect: 'ਨਕਸ਼ੇ ਤੇ ਟੈਪ',
    confirmLocation: 'ਜਗ੍ਹਾ ਪੱਕੀ', published: 'ਪ੍ਰਕਾਸ਼ਿਤ!', newListing: 'ਨਵੀਂ ਸੂਚੀ',
    stepOf: (n: number) => `ਕਦਮ ${n} / 3`,
    chooseCategory: 'ਸ਼੍ਰੇਣੀ', photosVideos: 'ਫੋਟੋ / ਵੀਡੀਓ', addMore: 'ਹੋਰ',
    priceUnit: 'ਮੁੱਲ ਇਕਾਈ', stockQty: 'ਸਟਾਕ', stockUnit: 'ਸਟਾਕ ਇਕਾਈ',
    productLocation: 'ਸਥਾਨ', pickLocation: 'ਨਕਸ਼ੇ ਤੇ ਟੈਪ',
    mobileNumber: 'ਮੋਬਾਈਲ', nextStep: 'ਅੱਗੇ', trustBadge: 'ਭਰੋਸਾ ਬੈਜ',
    identityUploaded: 'ਪਛਾਣ ਅਪ.', verifiedBadgeWill: 'Verified ਬੈਜ ਮਿਲੇਗਾ',
    uploadIdentity: 'ਪਛਾਣ ਅਪ.', description: 'ਵੇਰਵਾ', descriptionHint: 'ਗੁਣਵੱਤਾ…',
    newBtn: 'ਨਵੀਂ', active: 'ਸਕਿਰਿਆ', views: 'ਵਿਊ', leads: 'ਲੀਡ',
    activeListings: (n: number) => `${n} ਸਕਿਰਿਆ ਸੂਚੀਆਂ`,
    dukaanPortal: 'ਦੁਕਾਨ ਪੋਰਟਲ', manageShop: 'ਆਰਡਰ, ਇਨਵੈਂਟਰੀ',
    noListings: 'ਸੂਚੀਆਂ ਨਹੀਂ', sold: 'ਵਿਕਿਆ', avail: 'ਉ.',
    editListing: 'ਸੰਪਾਦਿਤ', preview: 'ਪੂਰਵਾਵਲੋਕਨ', delete: 'ਹਟਾਓ',
    deleteConfirm: 'ਸੂਚੀ ਹਟਾਓ?', undo: 'ਪੂਰਵਵਤ', listingDeleted: 'ਸੂਚੀ ਹਟਾਈ',
    becomeDukandaar: 'ਦੁਕਾਨਦਾਰ ਬਣੋ', becomeShopkeeper: 'ਦੁਕਾਨਦਾਰ ਬਣੋ →',
    buyerEnquiries: 'ਖਰੀਦਦਾਰ ਪੁੱਛਗਿੱਛ', reply: 'ਜਵਾਬ', edit: 'ਸੰਪਾਦਿਤ', availableQty: 'ਉ.',
    accountSettings: 'ਖਾਤਾ ਸੈਟਿੰਗ', personalInfo: 'ਨਿੱਜੀ', fullName: 'ਪੂਰਾ ਨਾਮ',
    languageLabel: 'ਭਾਸ਼ਾ', changePassword: 'ਪਾਸਵਰਡ ਬਦਲੋ',
    currentPwd: 'ਮੌਜੂਦਾ ਪਾ.', newPwd: 'ਨਵਾਂ ਪਾ.',
    minChars: 'ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ', saved: 'ਸੁਰੱਖਿਅਤ!', saveChanges: 'ਬਦਲਾਅ ਸੁਰੱਖਿਅਤ',
    notifications: 'ਸੂਚਨਾਵਾਂ', alerts: 'ਅਲਰਟ', channels: 'ਚੈਨਲ',
    aadhaarCard: 'ਆਧਾਰ', identityVerification: 'ਪਛਾਣ ਤਸਦੀਕ',
    panCard: 'PAN', taxId: 'ਕਰ ਪਛਾਣ', bankAccount: 'ਬੈਂਕ',
    linkPayments: 'ਭੁਗਤਾਨ ਲਿੰਕ', accountNumber: 'ਖਾਤਾ ਨੰ.', ifscCode: 'IFSC',
    linkAccount: 'ਖਾਤਾ ਲਿੰਕ', farmDetails: 'ਖੇਤ ਵੇਰਵਾ', farmerIdentity: 'ਕਿਸਾਨ ਪਛਾਣ',
    landArea: 'ਜ਼ਮੀਨ (ਏਕੜ)', satbaraNumber: '7/12 ਨੰ.',
    uploadSatbara: '7/12 ਫੋਟੋ', submitReview: 'ਸਮੀਖਿਆ',
    kycVerification: 'KYC', completion: 'ਪੂਰਨਤਾ',
    complete: '✓ ਪੂਰਾ', locked: '🔒 ਲਾਕ',
    helpSupport: 'ਸਹਾਇਤਾ', rateApp: 'ਰੇਟ ਕਰੋ',
    rateDesc: 'ਤੁਹਾਡੀ ਰਾਏ', faq: 'FAQ',
    callUs: 'ਕਾਲ', chatNow: 'ਚੈਟ', emailUs: 'ਈਮੇਲ',
    shopRegistration: 'ਦੁਕਾਨ ਨੋਂਦਣੀ', premiumFarmer: 'ਪ੍ਰੀਮੀਅਮ ਕਿਸਾਨ', myDukaan: 'ਮੇਰੀ ਦੁਕਾਨ',
    signOut: 'ਸਾਈਨ ਆਊਟ', signOutConfirm: 'ਸਾਈਨ ਆਊਟ?', signOutDesc: 'ਦੁਬਾਰਾ ਲਾਗਿਨ ਕਰੋ',
    verifiedStatus: 'ਤਸਦੀਕ · 12 ਜਨ 2025',
    listingsLabel: 'ਸੂਚੀਆਂ', ratingLabel: 'ਰੇਟਿੰਗ', salesLabel: 'ਵਿਕਰੀ',
    totalAmount: 'ਕੁੱਲ', tracking: 'ਟ੍ਰੈਕਿੰਗ',
    sellerLabel: 'ਵਿਕ੍ਰੇਤਾ', buyerLabel: 'ਖਰੀਦਦਾਰ', priceBreakdown: 'ਕੀਮਤ',
    itemTotal: 'ਵਸਤੂ', transportCost: 'ਆਵਾਜਾਈ', paymentLabel: 'ਭੁਗਤਾਨ',
    grandTotal: 'ਕੁੱਲ', swaSevaProtected: 'Swaseva ਸੁਰੱਖਿਅਤ',
    myTransactions: 'ਮੇਰੇ ਲੈਣ-ਦੇਣ', purchased: '🛒 ਖਰੀਦਿਆ', soldTab: '🌾 ਵੇਚਿਆ',
    ordersLabel: 'ਆਰਡਰ', spent: 'ਖਰਚ', earned: 'ਕਮਾਈ',
    swasevaLogistics: 'Swaseva ਲਾਜਿ.',
  },
  kn: {
    home: 'ಮಾರುಕಟ್ಟೆ',
    sell: 'ಮಾರಾಟ ಮಾಡಿ',
    listings: 'ಪಟ್ಟಿಗಳು',
    myShop: 'ನನ್ನ ಪಟ್ಟಿ',
    orders: 'ಆದೇಶಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    searchPlaceholder: 'ಬೀಜಗಳು, ಸಸಿಗಳನ್ನು ಹುಡುಕಿ...',
    nearYou: 'ನಿಮ್ಮ ಹತ್ತಿರ ಲಭ್ಯ',
    trusted: 'ನಂಬಲರ್ಹ ಮಾರಾಟಗಾರರು',
    viewDetails: 'ವಿವರ ನೋಡಿ',
    call: 'ಕರೆ ಮಾಡಿ',
    chat: 'ಚಾಟ್ ಮಾಡಿ',
    transport: 'ಸಾರಿಗೆ ಬೇಕೇ?',
    addInventory: 'ಮಾರಾಟ ಮಾಡಿ',
    publish: 'ಪ್ರಕಟಿಸಿ',
    variety: 'ತಳಿ',
    quantity: 'ಪ್ರಮಾಣ',
    price: 'ಬೆಲೆ',
    age: 'ವಯಸ್ಸು',
    location: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    noOrders: 'ಯಾವುದೇ ಆದೇಶಗಳಿಲ್ಲ',
    noOrdersDesc: 'ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಖರೀದಿ ಮತ್ತು ಮಾರಾಟ ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ.',
    startShopping: 'ಮಾರುಕಟ್ಟೆ ನೋಡಿ',
    unitsLabel: 'ನಗ',
    verifiedChoice: 'ಪರಿಶೀಲಿಸಿದ ಆಯ್ಕೆ',
    itemDetails: 'ವಸ್ತು ವಿವರ',
    qualityVerified: 'ಗುಣಮಟ್ಟ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    selfPickup: 'ಸ್ವಯಂ ತೆಗೆದುಕೊಳ್ಳಿ',
    requestTransport: 'ಸಾರಿಗೆ ಸಹಾಯ ಕೇಳಿ',
    messages: 'ಸಂದೇಶಗಳು',
    sendEnquiry: 'ವಿಚಾರಣೆ ಕಳುಹಿಸಿ',
    enquirySent: 'ವಿಚಾರಣೆ ಕಳುಹಿಸಲಾಗಿದೆ!',
    listingLocation: 'ಸ್ಥಳ',
    viewMap: 'ನಕ್ಷೆ ನೋಡಿ',
    comingSoon: 'ಶೀಘ್ರದಲ್ಲಿ ಬರಲಿದೆ',
    comingSoonDesc: 'ಸಾರಿಗೆ ಬುಕಿಂಗ್ ಶೀಘ್ರದಲ್ಲಿ ಲಭ್ಯವಾಗಲಿದೆ.',
    sellerProfile: 'ಮಾರಾಟಗಾರರ ಪ್ರೊಫೈಲ್',
    daysOnApp: 'App ನಲ್ಲಿ ದಿನಗಳು',
    itemsSold: 'ಮಾರಾಟವಾದ ವಸ್ತುಗಳು',
    otherListings: 'ಇತರ ಪಟ್ಟಿಗಳು',
    contactSeller: 'ಮಾರಾಟಗಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ',
    noMessages: 'ಯಾವುದೇ ಸಂದೇಶಗಳಿಲ್ಲ',
    noMessagesDesc: 'ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಲು ವಿಚಾರಣೆ ಕಳುಹಿಸಿ.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `ನಮಸ್ಕಾರ, Swaseva ನಲ್ಲಿ ನಿಮ್ಮ ${productName} (₹${price}/${unit}) ನೋಡಿದೆ. ದಯವಿಟ್ಟು ಹೆಚ್ಚಿನ ವಿವರ ನೀಡಿ.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `ನಮಸ್ಕಾರ, Swaseva ನಲ್ಲಿ ನಿಮ್ಮ ${productName} (₹${price}/${unit}) ನೋಡಿದೆ. ದಯವಿಟ್ಟು ಹೆಚ್ಚಿನ ವಿವರ ನೀಡಿ.`,
    cancel: 'ರದ್ದು', apply: 'ಅನ್ವಯ', reset: 'ರೀಸೆಟ್', loading: 'ಲೋಡ್…',
    newsImpact: 'ಸುದ್ದಿ ಮತ್ತು ಪ್ರಭಾವ', newsDesc: 'ಕೃಷಿ ಸುದ್ದಿ, MSP ಅಪ್ಡೇಟ್',
    nearbyShops: 'ಹತ್ತಿರದ ಅಂಗಡಿಗಳು', seeAll: 'ಎಲ್ಲ →', freshListings: 'ಹೊಸ ಪಟ್ಟಿಗಳು',
    allIndia: 'ಇಡೀ ಭಾರತ', all: 'ಎಲ್ಲ', agriInputs: 'ಕೃಷಿ ಸಾಮಗ್ರಿ',
    noProducts: 'ಉತ್ಪನ್ನಗಳಿಲ್ಲ', fromOtherAreas: 'ಇತರ ಪ್ರದೇಶಗಳಿಂದ',
    compareCount: (n: number) => `${n} ಹೋಲಿಕೆ`,
    filterSort: 'ಫಿಲ್ಟರ್', sortBy: 'ಕ್ರಮ', newest: 'ಹೊಸದು',
    priceLow: 'ಕಡಿಮೆ ಬೆಲೆ', priceHigh: 'ಹೆಚ್ಚು ಬೆಲೆ', priceRange: 'ಬೆಲೆ (₹)',
    min: 'ಕನಿಷ್ಠ', max: 'ಗರಿಷ್ಠ',
    farmLocation: 'ಹೊಲದ ಸ್ಥಳ', tapMapDrag: 'ನಕ್ಷೆ ಟ್ಯಾಪ್ ಮಾಡಿ',
    gettingAddress: 'ವಿಳಾಸ…', tapMapSelect: 'ನಕ್ಷೆ ಟ್ಯಾಪ್',
    confirmLocation: 'ಸ್ಥಳ ದೃಢ', published: 'ಪ್ರಕಟ!', newListing: 'ಹೊಸ ಪಟ್ಟಿ',
    stepOf: (n: number) => `ಹಂತ ${n} / 3`,
    chooseCategory: 'ವರ್ಗ', photosVideos: 'ಫೋಟೋ / ವೀಡಿಯೋ', addMore: 'ಹೆಚ್ಚು',
    priceUnit: 'ಬೆಲೆ ಘಟಕ', stockQty: 'ಸ್ಟಾಕ್', stockUnit: 'ಸ್ಟಾಕ್ ಘಟಕ',
    productLocation: 'ಸ್ಥಳ', pickLocation: 'ನಕ್ಷೆ ಟ್ಯಾಪ್',
    mobileNumber: 'ಮೊಬೈಲ್', nextStep: 'ಮುಂದೆ', trustBadge: 'ವಿಶ್ವಾಸ ಬ್ಯಾಡ್ಜ್',
    identityUploaded: 'ಗುರುತು ಅಪ್.', verifiedBadgeWill: 'Verified ಬ್ಯಾಡ್ಜ್ ಬರುತ್ತದೆ',
    uploadIdentity: 'ಗುರುತು ಅಪ್.', description: 'ವಿವರಣೆ', descriptionHint: 'ಗುಣಮಟ್ಟ…',
    newBtn: 'ಹೊಸದು', active: 'ಸಕ್ರಿಯ', views: 'ವ್ಯೂ', leads: 'ಲೀಡ್',
    activeListings: (n: number) => `${n} ಸಕ್ರಿಯ`,
    dukaanPortal: 'ಅಂಗಡಿ ಪೋರ್ಟಲ್', manageShop: 'ಆರ್ಡರ್, ಇನ್ವೆಂಟರಿ',
    noListings: 'ಪಟ್ಟಿಗಳಿಲ್ಲ', sold: 'ಮಾರಿದೆ', avail: 'ಲ.',
    editListing: 'ಸಂಪಾದಿಸಿ', preview: 'ಮೊದಲು ನೋಡಿ', delete: 'ತೆಗೆದುಹಾಕಿ',
    deleteConfirm: 'ಪಟ್ಟಿ ತೆಗೆಯಲೇ?', undo: 'ರದ್ದು', listingDeleted: 'ಪಟ್ಟಿ ತೆಗೆದಿದೆ',
    becomeDukandaar: 'ಅಂಗಡಿಯವರಾಗಿ ನೋಂದಾಯಿಸಿ', becomeShopkeeper: 'ಅಂಗಡಿಯವರಾಗಿ →',
    buyerEnquiries: 'ಖರೀದಿದಾರ ವಿಚಾರಣೆ', reply: 'ಉತ್ತರ', edit: 'ಸಂಪಾದಿಸಿ', availableQty: 'ಲ.',
    accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್', personalInfo: 'ವೈಯಕ್ತಿಕ', fullName: 'ಹೆಸರು',
    languageLabel: 'ಭಾಷೆ', changePassword: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
    currentPwd: 'ಹಳೆ ಪಾ.', newPwd: 'ಹೊಸ ಪಾ.',
    minChars: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರ', saved: 'ಉಳಿಸಲಾಗಿದೆ!', saveChanges: 'ಉಳಿಸಿ',
    notifications: 'ಅಧಿಸೂಚನೆ', alerts: 'ಎಚ್ಚರಿಕೆ', channels: 'ಚಾನಲ್',
    aadhaarCard: 'ಆಧಾರ್', identityVerification: 'ಗುರುತು ಪರಿಶೀಲನೆ',
    panCard: 'PAN', taxId: 'ತೆರಿಗೆ', bankAccount: 'ಬ್ಯಾಂಕ್',
    linkPayments: 'ಪಾವತಿ ಲಿಂಕ್', accountNumber: 'ಖಾತೆ ನಂ.', ifscCode: 'IFSC',
    linkAccount: 'ಖಾತೆ ಲಿಂಕ್', farmDetails: 'ಹೊಲ ವಿವರ', farmerIdentity: 'ರೈತ ಗುರುತು',
    landArea: 'ಜಮೀನು (ಎಕರೆ)', satbaraNumber: '7/12 ನಂ.',
    uploadSatbara: '7/12 ಫೋಟೋ', submitReview: 'ಸಮೀಕ್ಷೆ',
    kycVerification: 'KYC', completion: 'ಪೂರ್ಣ',
    complete: '✓ ಪೂರ್ಣ', locked: '🔒 ಲಾಕ್',
    helpSupport: 'ಸಹಾಯ', rateApp: 'ರೇಟ್ ಮಾಡಿ',
    rateDesc: 'ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ', faq: 'FAQ',
    callUs: 'ಕರೆ', chatNow: 'ಚಾಟ್', emailUs: 'ಇಮೇಲ್',
    shopRegistration: 'ಅಂಗಡಿ ನೋಂದಣಿ', premiumFarmer: 'ಪ್ರೀಮಿಯಂ ರೈತ', myDukaan: 'ನನ್ನ ಅಂಗಡಿ',
    signOut: 'ಸೈನ್ ಔಟ್', signOutConfirm: 'ಸೈನ್ ಔಟ್?', signOutDesc: 'ಮತ್ತೆ ಲಾಗಿನ್ ಆಗಬೇಕು',
    verifiedStatus: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ · 12 ಜನ 2025',
    listingsLabel: 'ಪಟ್ಟಿಗಳು', ratingLabel: 'ರೇಟಿಂಗ್', salesLabel: 'ಮಾರಾಟ',
    totalAmount: 'ಒಟ್ಟು', tracking: 'ಟ್ರ್ಯಾಕಿಂಗ್',
    sellerLabel: 'ವಿಕ್ರೇಟ', buyerLabel: 'ಖರೀದಿದಾರ', priceBreakdown: 'ಬೆಲೆ',
    itemTotal: 'ವಸ್ತು', transportCost: 'ಸಾರಿಗೆ', paymentLabel: 'ಪಾವತಿ',
    grandTotal: 'ಒಟ್ಟು', swaSevaProtected: 'Swaseva ರಕ್ಷಿತ',
    myTransactions: 'ನನ್ನ ವ್ಯವಹಾರ', purchased: '🛒 ಖರೀದಿ', soldTab: '🌾 ಮಾರಿದೆ',
    ordersLabel: 'ಆರ್ಡರ್', spent: 'ಖರ್ಚು', earned: 'ಗಳಿಕೆ',
    swasevaLogistics: 'Swaseva ಲಾಜಿ.',
  },
  ta: {
    home: 'சந்தை',
    sell: 'விற்கவும்',
    listings: 'பட்டியல்கள்',
    myShop: 'என் பட்டியல்',
    orders: 'ஆர்டர்கள்',
    profile: 'சுயவிவரம்',
    searchPlaceholder: 'விதைகள், நாற்றுகள் தேடவும்...',
    nearYou: 'உங்களுக்கு அருகில் கிடைக்கும்',
    trusted: 'நம்பகமான விற்பனையாளர்கள்',
    viewDetails: 'விவரம் காண்க',
    call: 'அழைக்கவும்',
    chat: 'அரட்டை அடிக்கவும்',
    transport: 'போக்குவரத்து வேண்டுமா?',
    addInventory: 'விற்கவும்',
    publish: 'பதிப்பிக்கவும்',
    variety: 'இனம்',
    quantity: 'அளவு',
    price: 'விலை',
    age: 'வயது',
    location: 'தற்போதைய இடம்',
    noOrders: 'ஆர்டர்கள் இல்லை',
    noOrdersDesc: 'உங்கள் சமீபத்திய கொள்முதல் மற்றும் விற்பனை இங்கே காட்டப்படும்.',
    startShopping: 'சந்தையை பாருங்கள்',
    unitsLabel: 'நகம்',
    verifiedChoice: 'சரிபார்க்கப்பட்ட தேர்வு',
    itemDetails: 'பொருள் விவரம்',
    qualityVerified: 'தரம் சரிபார்க்கப்பட்டது',
    selfPickup: 'நேரில் எடுக்கவும்',
    requestTransport: 'போக்குவரத்து உதவி கோரவும்',
    messages: 'செய்திகள்',
    sendEnquiry: 'விசாரணை அனுப்பவும்',
    enquirySent: 'விசாரணை அனுப்பப்பட்டது!',
    listingLocation: 'இடம்',
    viewMap: 'வரைபடம் காண்க',
    comingSoon: 'விரைவில் வருகிறது',
    comingSoonDesc: 'போக்குவரத்து முன்பதிவு விரைவில் கிடைக்கும்.',
    sellerProfile: 'விற்பனையாளர் சுயவிவரம்',
    daysOnApp: 'App-ல் நாட்கள்',
    itemsSold: 'விற்கப்பட்ட பொருட்கள்',
    otherListings: 'மற்ற பட்டியல்கள்',
    contactSeller: 'விற்பனையாளரை தொடர்பு கொள்ளவும்',
    noMessages: 'செய்திகள் இல்லை',
    noMessagesDesc: 'உரையாடல் தொடங்க விசாரணை அனுப்பவும்.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `வணக்கம், Swaseva-ல் உங்கள் ${productName} (₹${price}/${unit}) பார்த்தேன். மேலும் விவரங்கள் தரவும்.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `வணக்கம், Swaseva-ல் உங்கள் ${productName} (₹${price}/${unit}) பார்த்தேன். மேலும் விவரங்கள் தரவும்.`,
    cancel: 'ரத்து', apply: 'பயன்படுத்து', reset: 'மீட்டமை', loading: 'ஏற்றுகிறது…',
    newsImpact: 'செய்திகள் மற்றும் தாக்கம்', newsDesc: 'விவசாய செய்திகள், MSP',
    nearbyShops: 'அருகிலுள்ள கடைகள்', seeAll: 'அனைத்தும் →', freshListings: 'புதிய பட்டியல்கள்',
    allIndia: 'இந்தியா முழுவதும்', all: 'அனைத்தும்', agriInputs: 'விவசாய பொருட்கள்',
    noProducts: 'பொருட்கள் இல்லை', fromOtherAreas: 'மற்ற பகுதிகளிலிருந்து',
    compareCount: (n: number) => `${n} ஒப்பீடு`,
    filterSort: 'வடிகட்டு', sortBy: 'வரிசை', newest: 'புதியது',
    priceLow: 'குறைந்த விலை', priceHigh: 'அதிக விலை', priceRange: 'விலை (₹)',
    min: 'குறைந்தபட்சம்', max: 'அதிகபட்சம்',
    farmLocation: 'வயல் இடம்', tapMapDrag: 'வரைபடத்தில் தட்டவும்',
    gettingAddress: 'முகவரி…', tapMapSelect: 'வரைபட தட்டு',
    confirmLocation: 'இடம் உறுதி', published: 'வெளியிடப்பட்டது!', newListing: 'புதிய பட்டியல்',
    stepOf: (n: number) => `படி ${n} / 3`,
    chooseCategory: 'வகை தேர்வு', photosVideos: 'புகைப்படம் / வீடியோ', addMore: 'மேலும்',
    priceUnit: 'விலை அலகு', stockQty: 'சரக்கு', stockUnit: 'சரக்கு அலகு',
    productLocation: 'இடம்', pickLocation: 'வரைபட தட்டு',
    mobileNumber: 'மொபைல்', nextStep: 'அடுத்து', trustBadge: 'நம்பகம் பேட்ஜ்',
    identityUploaded: 'அடையாளம் பதிவு', verifiedBadgeWill: 'Verified பேட்ஜ் கிடைக்கும்',
    uploadIdentity: 'அடையாளம் பதிவு', description: 'விளக்கம்', descriptionHint: 'தரம்…',
    newBtn: 'புதியது', active: 'செயலில்', views: 'பார்வைகள்', leads: 'லீட்கள்',
    activeListings: (n: number) => `${n} செயலில்`,
    dukaanPortal: 'கடை போர்டல்', manageShop: 'ஆர்டர்கள், சரக்கு',
    noListings: 'பட்டியல்கள் இல்லை', sold: 'விற்றது', avail: 'கி.',
    editListing: 'திருத்து', preview: 'முன்னோட்டம்', delete: 'நீக்கு',
    deleteConfirm: 'பட்டியல் நீக்கவா?', undo: 'மீட்டமை', listingDeleted: 'பட்டியல் நீக்கப்பட்டது',
    becomeDukandaar: 'கடையாளராக பதிவு', becomeShopkeeper: 'கடையாளர் ஆகுங்கள் →',
    buyerEnquiries: 'வாங்குபவர் விசாரணை', reply: 'பதில்', edit: 'திருத்து', availableQty: 'கி.',
    accountSettings: 'கணக்கு அமைப்பு', personalInfo: 'தனிப்பட்ட', fullName: 'பெயர்',
    languageLabel: 'மொழி', changePassword: 'கடவுச்சொல் மாற்று',
    currentPwd: 'பழைய கட.', newPwd: 'புதிய கட.',
    minChars: 'குறைந்தது 8 எழுத்துகள்', saved: 'சேமிக்கப்பட்டது!', saveChanges: 'மாற்றங்கள் சேமி',
    notifications: 'அறிவிப்புகள்', alerts: 'எச்சரிக்கைகள்', channels: 'சேனல்கள்',
    aadhaarCard: 'ஆதார்', identityVerification: 'அடையாள சரிபார்ப்பு',
    panCard: 'PAN', taxId: 'வரி அடையாளம்', bankAccount: 'வங்கி',
    linkPayments: 'கட்டணம் இணை', accountNumber: 'கணக்கு எண்', ifscCode: 'IFSC',
    linkAccount: 'கணக்கு இணை', farmDetails: 'வயல் விவரம்', farmerIdentity: 'விவசாயி அடையாளம்',
    landArea: 'நிலம் (ஏக்கர்)', satbaraNumber: '7/12 எண்.',
    uploadSatbara: '7/12 புகைப்படம்', submitReview: 'மதிப்பாய்வு',
    kycVerification: 'KYC', completion: 'பூர்த்தி',
    complete: '✓ பூர்த்தி', locked: '🔒 பூட்டு',
    helpSupport: 'உதவி', rateApp: 'மதிப்பிடுங்கள்',
    rateDesc: 'உங்கள் கருத்து', faq: 'FAQ',
    callUs: 'அழைப்பு', chatNow: 'அரட்டை', emailUs: 'மின்னஞ்சல்',
    shopRegistration: 'கடை பதிவு', premiumFarmer: 'பிரீமியம் விவசாயி', myDukaan: 'என் கடை',
    signOut: 'வெளியேறு', signOutConfirm: 'வெளியேறவா?', signOutDesc: 'மீண்டும் உள்நுழைய வேண்டும்',
    verifiedStatus: 'சரிபார்க்கப்பட்டது · 12 ஜன 2025',
    listingsLabel: 'பட்டியல்கள்', ratingLabel: 'மதிப்பீடு', salesLabel: 'விற்பனை',
    totalAmount: 'மொத்தம்', tracking: 'கண்காணிப்பு',
    sellerLabel: 'விற்பனையாளர்', buyerLabel: 'வாங்குபவர்', priceBreakdown: 'விலை',
    itemTotal: 'பொருள்', transportCost: 'போக்குவரத்து', paymentLabel: 'கட்டணம்',
    grandTotal: 'மொத்தம்', swaSevaProtected: 'Swaseva பாதுகாப்பு',
    myTransactions: 'என் பரிமாற்றங்கள்', purchased: '🛒 வாங்கியது', soldTab: '🌾 விற்றது',
    ordersLabel: 'ஆர்டர்கள்', spent: 'செலவு', earned: 'வருமானம்',
    swasevaLogistics: 'Swaseva தளவாட',
  },
  bn: {
    home: 'বাজার',
    sell: 'বিক্রি করুন',
    listings: 'তালিকা',
    myShop: 'আমার তালিকা',
    orders: 'অর্ডার',
    profile: 'প্রোফাইল',
    searchPlaceholder: 'বীজ, চারা খুঁজুন...',
    nearYou: 'আপনার কাছে পাওয়া যাচ্ছে',
    trusted: 'বিশ্বস্ত বিক্রেতা',
    viewDetails: 'বিস্তারিত দেখুন',
    call: 'ফোন করুন',
    chat: 'চ্যাট করুন',
    transport: 'পরিবহন দরকার?',
    addInventory: 'বিক্রি করুন',
    publish: 'প্রকাশ করুন',
    variety: 'জাত',
    quantity: 'পরিমাণ',
    price: 'মূল্য',
    age: 'বয়স',
    location: 'বর্তমান স্থান',
    noOrders: 'কোনো অর্ডার নেই',
    noOrdersDesc: 'আপনার সাম্প্রতিক কেনাকাটা এবং বিক্রয় এখানে দেখা যাবে।',
    startShopping: 'বাজার দেখুন',
    unitsLabel: 'নং',
    verifiedChoice: 'যাচাইকৃত পছন্দ',
    itemDetails: 'পণ্যের বিবরণ',
    qualityVerified: 'গুণমান যাচাই করা হয়েছে',
    selfPickup: 'নিজে তুলে নিন',
    requestTransport: 'পরিবহন সহায়তা চান',
    messages: 'বার্তা',
    sendEnquiry: 'অনুসন্ধান পাঠান',
    enquirySent: 'অনুসন্ধান পাঠানো হয়েছে!',
    listingLocation: 'স্থান',
    viewMap: 'মানচিত্র দেখুন',
    comingSoon: 'শীঘ্রই আসছে',
    comingSoonDesc: 'পরিবহন বুকিং শীঘ্রই উপলব্ধ হবে।',
    sellerProfile: 'বিক্রেতার প্রোফাইল',
    daysOnApp: 'App-এ দিন',
    itemsSold: 'বিক্রি হওয়া পণ্য',
    otherListings: 'অন্যান্য তালিকা',
    contactSeller: 'বিক্রেতার সাথে যোগাযোগ করুন',
    noMessages: 'কোনো বার্তা নেই',
    noMessagesDesc: 'কথোপকথন শুরু করতে অনুসন্ধান পাঠান।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `নমস্কার, Swaseva-তে আপনার ${productName} (₹${price}/${unit}) দেখলাম। দয়া করে আরো তথ্য দিন।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `নমস্কার, Swaseva-তে আপনার ${productName} (₹${price}/${unit}) দেখলাম। দয়া করে আরো তথ্য দিন।`,
    cancel: 'বাতিল', apply: 'প্রয়োগ', reset: 'রিসেট', loading: 'লোড হচ্ছে…',
    newsImpact: 'সংবাদ ও প্রভাব', newsDesc: 'কৃষি সংবাদ, MSP আপডেট',
    nearbyShops: 'কাছের দোকান', seeAll: 'সব →', freshListings: 'নতুন তালিকা',
    allIndia: 'সমগ্র ভারত', all: 'সব', agriInputs: 'কৃষি সামগ্রী',
    noProducts: 'কোনো পণ্য নেই', fromOtherAreas: 'অন্য এলাকা থেকে',
    compareCount: (n: number) => `${n} তুলনা`,
    filterSort: 'ফিল্টার', sortBy: 'ক্রম', newest: 'নতুন',
    priceLow: 'কম দাম', priceHigh: 'বেশি দাম', priceRange: 'দাম (₹)',
    min: 'সর্বনিম্ন', max: 'সর্বোচ্চ',
    farmLocation: 'খামারের জায়গা', tapMapDrag: 'মানচিত্রে ট্যাপ করুন',
    gettingAddress: 'ঠিকানা…', tapMapSelect: 'মানচিত্রে ট্যাপ',
    confirmLocation: 'জায়গা নিশ্চিত', published: 'প্রকাশিত!', newListing: 'নতুন তালিকা',
    stepOf: (n: number) => `ধাপ ${n} / 3`,
    chooseCategory: 'বিভাগ', photosVideos: 'ছবি / ভিডিও', addMore: 'আরো',
    priceUnit: 'মূল্য একক', stockQty: 'স্টক', stockUnit: 'স্টক একক',
    productLocation: 'স্থান', pickLocation: 'মানচিত্রে ট্যাপ',
    mobileNumber: 'মোবাইল', nextStep: 'পরবর্তী', trustBadge: 'বিশ্বাস ব্যাজ',
    identityUploaded: 'পরিচয় আপ.', verifiedBadgeWill: 'Verified ব্যাজ পাবেন',
    uploadIdentity: 'পরিচয় আপ.', description: 'বিবরণ', descriptionHint: 'গুণমান…',
    newBtn: 'নতুন', active: 'সক্রিয়', views: 'ভিউ', leads: 'লিড',
    activeListings: (n: number) => `${n} সক্রিয় তালিকা`,
    dukaanPortal: 'দোকান পোর্টাল', manageShop: 'অর্ডার, ইনভেন্টরি',
    noListings: 'তালিকা নেই', sold: 'বিক্রি', avail: 'উপ.',
    editListing: 'সম্পাদনা', preview: 'পূর্বরূপ', delete: 'মুছুন',
    deleteConfirm: 'তালিকা মুছবেন?', undo: 'পূর্বাবস্থা', listingDeleted: 'তালিকা মুছে গেছে',
    becomeDukandaar: 'দোকানদার হিসেবে নিবন্ধন', becomeShopkeeper: 'দোকানদার হন →',
    buyerEnquiries: 'ক্রেতার অনুসন্ধান', reply: 'উত্তর', edit: 'সম্পাদনা', availableQty: 'উপ.',
    accountSettings: 'অ্যাকাউন্ট সেটিং', personalInfo: 'ব্যক্তিগত', fullName: 'নাম',
    languageLabel: 'ভাষা', changePassword: 'পাসওয়ার্ড পরিবর্তন',
    currentPwd: 'পুরনো পা.', newPwd: 'নতুন পা.',
    minChars: 'কমপক্ষে 8 অক্ষর', saved: 'সংরক্ষিত!', saveChanges: 'পরিবর্তন সংরক্ষণ',
    notifications: 'বিজ্ঞপ্তি', alerts: 'সতর্কতা', channels: 'চ্যানেল',
    aadhaarCard: 'আধার', identityVerification: 'পরিচয় যাচাই',
    panCard: 'PAN', taxId: 'কর পরিচয়', bankAccount: 'ব্যাংক',
    linkPayments: 'পেমেন্ট লিংক', accountNumber: 'অ্যাকাউন্ট নং.', ifscCode: 'IFSC',
    linkAccount: 'অ্যাকাউন্ট লিংক', farmDetails: 'খামার বিবরণ', farmerIdentity: 'কৃষক পরিচয়',
    landArea: 'জমি (একর)', satbaraNumber: '7/12 নম্বর',
    uploadSatbara: '7/12 ছবি', submitReview: 'পর্যালোচনা',
    kycVerification: 'KYC', completion: 'সম্পূর্ণতা',
    complete: '✓ সম্পূর্ণ', locked: '🔒 লক',
    helpSupport: 'সহায়তা', rateApp: 'রেট করুন',
    rateDesc: 'আপনার মতামত', faq: 'FAQ',
    callUs: 'কল', chatNow: 'চ্যাট', emailUs: 'ইমেইল',
    shopRegistration: 'দোকান নিবন্ধন', premiumFarmer: 'প্রিমিয়াম কৃষক', myDukaan: 'আমার দোকান',
    signOut: 'সাইন আউট', signOutConfirm: 'সাইন আউট?', signOutDesc: 'আবার লগইন করতে হবে',
    verifiedStatus: 'যাচাই · 12 জান 2025',
    listingsLabel: 'তালিকা', ratingLabel: 'রেটিং', salesLabel: 'বিক্রয়',
    totalAmount: 'মোট', tracking: 'ট্র্যাকিং',
    sellerLabel: 'বিক্রেতা', buyerLabel: 'ক্রেতা', priceBreakdown: 'দাম',
    itemTotal: 'পণ্য', transportCost: 'পরিবহন', paymentLabel: 'পেমেন্ট',
    grandTotal: 'মোট', swaSevaProtected: 'Swaseva সুরক্ষিত',
    myTransactions: 'আমার লেনদেন', purchased: '🛒 কেনা', soldTab: '🌾 বিক্রি',
    ordersLabel: 'অর্ডার', spent: 'ব্যয়', earned: 'আয়',
    swasevaLogistics: 'Swaseva লজিস্টিক্স',
  },
  or: {
    home: 'ବଜାର',
    sell: 'ବିକ୍ରି କରନ୍ତୁ',
    listings: 'ତାଲିକା',
    myShop: 'ମୋ ତାଲିକା',
    orders: 'ଅର୍ଡର',
    profile: 'ପ୍ରୋଫାଇଲ',
    searchPlaceholder: 'ବୀଜ, ଚାରା ଖୋଜନ୍ତୁ...',
    nearYou: 'ଆପଣଙ୍କ ନିକଟରେ ଉପଲବ୍ଧ',
    trusted: 'ବିଶ୍ୱସ୍ତ ବିକ୍ରେତା',
    viewDetails: 'ବିବରଣ ଦେଖନ୍ତୁ',
    call: 'ଫୋନ୍ କରନ୍ତୁ',
    chat: 'ଚ୍ୟାଟ୍ କରନ୍ତୁ',
    transport: 'ପରିବହନ ଦରକାର?',
    addInventory: 'ବିକ୍ରି କରନ୍ତୁ',
    publish: 'ପ୍ରକାଶ କରନ୍ତୁ',
    variety: 'ଜାତ',
    quantity: 'ପରିମାଣ',
    price: 'ମୂଲ୍ୟ',
    age: 'ବୟସ',
    location: 'ବର୍ତ୍ତମାନ ସ୍ଥାନ',
    noOrders: 'କୌଣସି ଅର୍ଡର ନାହିଁ',
    noOrdersDesc: 'ଆପଣଙ୍କ ସାମ୍ପ୍ରତିକ କ୍ରୟ ଏବଂ ବିକ୍ରୟ ଏଠାରେ ଦେଖାଯିବ।',
    startShopping: 'ବଜାର ଦେଖନ୍ତୁ',
    unitsLabel: 'ନଗ',
    verifiedChoice: 'ଯାଞ୍ଚ ହୋଇଥିବା ବିକଳ୍ପ',
    itemDetails: 'ଜିନିଷ ବିବରଣ',
    qualityVerified: 'ଗୁଣବତ୍ତା ଯାଞ୍ଚ',
    selfPickup: 'ନିଜେ ନିଅନ୍ତୁ',
    requestTransport: 'ପରିବହନ ସହାୟତା ଚାହୁଁଛନ୍ତି',
    messages: 'ବାର୍ତ୍ତା',
    sendEnquiry: 'ଅନୁସନ୍ଧାନ ପଠାନ୍ତୁ',
    enquirySent: 'ଅନୁସନ୍ଧାନ ପଠାଯାଇଛି!',
    listingLocation: 'ସ୍ଥାନ',
    viewMap: 'ମ୍ୟାପ୍ ଦେଖନ୍ତୁ',
    comingSoon: 'ଶୀଘ୍ର ଆସୁଛି',
    comingSoonDesc: 'ପରିବହନ ବୁକିଂ ଶୀଘ୍ର ଉପଲବ୍ଧ ହେବ।',
    sellerProfile: 'ବିକ୍ରେତା ପ୍ରୋଫାଇଲ',
    daysOnApp: 'App ରେ ଦିନ',
    itemsSold: 'ବିକ୍ରି ହୋଇଥିବା ଜିନିଷ',
    otherListings: 'ଅନ୍ୟ ତାଲିକା',
    contactSeller: 'ବିକ୍ରେତାଙ୍କ ସହ ଯୋଗାଯୋଗ',
    noMessages: 'କୌଣସି ବାର୍ତ୍ତା ନାହିଁ',
    noMessagesDesc: 'ବାର୍ତ୍ତାଳାପ ଆରମ୍ଭ କରିବାକୁ ଅନୁସନ୍ଧାନ ପଠାନ୍ତୁ।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `ନମସ୍କାର, Swaseva ରେ ଆପଣଙ୍କ ${productName} (₹${price}/${unit}) ଦେଖିଲି। ଦୟାକରି ଅଧିକ ତଥ୍ୟ ଦିଅନ୍ତୁ।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `ନମସ୍କାର, Swaseva ରେ ଆପଣଙ୍କ ${productName} (₹${price}/${unit}) ଦେଖିଲି। ଦୟାକରି ଅଧିକ ତଥ୍ୟ ଦିଅନ୍ତୁ।`,
    cancel: 'ବାତିଲ', apply: 'ଲାଗୁ', reset: 'ରିସେଟ', loading: 'ଲୋଡ…',
    newsImpact: 'ସମ୍ବାଦ ଓ ପ୍ରଭାବ', newsDesc: 'କୃଷି ସମ୍ବାଦ, MSP',
    nearbyShops: 'ନିକଟ ଦୋକାନ', seeAll: 'ସବୁ →', freshListings: 'ନୂଆ ତାଲିକା',
    allIndia: 'ସମ୍ପୂର୍ଣ୍ଣ ଭାରତ', all: 'ସବୁ', agriInputs: 'କୃଷି ସାମଗ୍ରୀ',
    noProducts: 'ଉତ୍ପାଦ ନାହିଁ', fromOtherAreas: 'ଅନ୍ୟ ଅଞ୍ଚଳରୁ',
    compareCount: (n: number) => `${n} ତୁଳନା`,
    filterSort: 'ଫିଲ୍ଟର', sortBy: 'କ୍ରମ', newest: 'ନୂଆ',
    priceLow: 'କମ ମୂଲ୍ୟ', priceHigh: 'ଅଧିକ ମୂଲ୍ୟ', priceRange: 'ମୂଲ୍ୟ (₹)',
    min: 'ସର୍ବନ୍ୟୂନ', max: 'ସର୍ବୋଚ୍ଚ',
    farmLocation: 'ଖେତ ସ୍ଥାନ', tapMapDrag: 'ମ୍ୟାପରେ ଟ୍ୟାପ',
    gettingAddress: 'ଠିକଣା…', tapMapSelect: 'ମ୍ୟାପ ଟ୍ୟାପ',
    confirmLocation: 'ସ୍ଥାନ ନିଶ୍ଚିତ', published: 'ପ୍ରକାଶ!', newListing: 'ନୂଆ ତାଲିକା',
    stepOf: (n: number) => `ଧାପ ${n} / 3`,
    chooseCategory: 'ବର୍ଗ', photosVideos: 'ଫୋଟୋ / ଭିଡିଓ', addMore: 'ଆଉ',
    priceUnit: 'ମୂଲ୍ୟ ଏକକ', stockQty: 'ଷ୍ଟକ', stockUnit: 'ଷ୍ଟକ ଏକକ',
    productLocation: 'ସ୍ଥାନ', pickLocation: 'ମ୍ୟାପ ଟ୍ୟାପ',
    mobileNumber: 'ମୋବାଇଲ', nextStep: 'ପରବର୍ତ୍ତୀ', trustBadge: 'ବିଶ୍ୱାସ ବ୍ୟାଜ',
    identityUploaded: 'ପରିଚୟ ଅ.', verifiedBadgeWill: 'Verified ବ୍ୟାଜ ମିଳିବ',
    uploadIdentity: 'ପରିଚୟ ଅ.', description: 'ବିବରଣ', descriptionHint: 'ଗୁଣ…',
    newBtn: 'ନୂଆ', active: 'ସକ୍ରିୟ', views: 'ଭ୍ୟୁ', leads: 'ଲୀଡ',
    activeListings: (n: number) => `${n} ସକ୍ରିୟ`,
    dukaanPortal: 'ଦୋକାନ ପୋର୍ଟାଲ', manageShop: 'ଅର୍ଡର, ଇ.',
    noListings: 'ତାଲିକା ନାହିଁ', sold: 'ବିକ୍ରି', avail: 'ଉ.',
    editListing: 'ସ.', preview: 'ପୂ.', delete: 'ହଟାଅ',
    deleteConfirm: 'ତାଲିକା ହଟାଇବ?', undo: 'ଫେରି', listingDeleted: 'ତାଲିକା ହଟେଇ',
    becomeDukandaar: 'ଦୋକାନଦାର ନୋଂଦ', becomeShopkeeper: 'ଦୋକାନ ହୁଅ →',
    buyerEnquiries: 'କ୍ରେତା ପ.', reply: 'ଉ.', edit: 'ସ.', availableQty: 'ଉ.',
    accountSettings: 'ଖ. ସେ.', personalInfo: 'ବ.', fullName: 'ନାମ',
    languageLabel: 'ଭାଷା', changePassword: 'ପା. ବ.',
    currentPwd: 'ପୁ. ପ.', newPwd: 'ନ. ପ.',
    minChars: 'ନ୍ୟୂ. 8 ଅ.', saved: 'ସ.!', saveChanges: 'ସ.',
    notifications: 'ସୂ.', alerts: 'ସ.', channels: 'ଚ.',
    aadhaarCard: 'ଆ.', identityVerification: 'ପ. ଯ.',
    panCard: 'PAN', taxId: 'କ.', bankAccount: 'ବ.',
    linkPayments: 'ପ. ଲ.', accountNumber: 'ଖ. ନ.', ifscCode: 'IFSC',
    linkAccount: 'ଖ. ଲ.', farmDetails: 'ଖ. ବ.', farmerIdentity: 'କ. ପ.',
    landArea: 'ଜ. (ଏ.)', satbaraNumber: '7/12',
    uploadSatbara: '7/12 ଫ.', submitReview: 'ସ.',
    kycVerification: 'KYC', completion: 'ପୂ.',
    complete: '✓ ପ.', locked: '🔒 ଲ.',
    helpSupport: 'ସ.', rateApp: 'ର.',
    rateDesc: 'ମ.', faq: 'FAQ',
    callUs: 'ଫ.', chatNow: 'ଚ.', emailUs: 'ଇ.',
    shopRegistration: 'ଦ. ନ.', premiumFarmer: 'ପ. କ.', myDukaan: 'ମ. ଦ.',
    signOut: 'ବ. ହ.', signOutConfirm: 'ବ. ହ.?', signOutDesc: 'ଫ. ଲ. ହ.',
    verifiedStatus: 'ଯ. · 12 ଜ. 2025',
    listingsLabel: 'ତ.', ratingLabel: 'ର.', salesLabel: 'ବ.',
    totalAmount: 'ମ.', tracking: 'ଟ.',
    sellerLabel: 'ବ.', buyerLabel: 'କ.', priceBreakdown: 'ମ.',
    itemTotal: 'ଜ.', transportCost: 'ପ.', paymentLabel: 'ଦ.',
    grandTotal: 'ମ.', swaSevaProtected: 'Swaseva ସ.',
    myTransactions: 'ମ. ଲ.', purchased: '🛒 କ.', soldTab: '🌾 ବ.',
    ordersLabel: 'ଅ.', spent: 'ଖ.', earned: 'ଆ.',
    swasevaLogistics: 'Swaseva ଲ.',
  },
  ml: {
    home: 'മാർക്കറ്റ്',
    sell: 'വിൽക്കുക',
    listings: 'ലിസ്റ്റിംഗ്',
    myShop: 'എന്റെ ലിസ്റ്റ്',
    orders: 'ഓർഡറുകൾ',
    profile: 'പ്രൊഫൈൽ',
    searchPlaceholder: 'വിത്തുകൾ, തൈകൾ തിരയുക...',
    nearYou: 'നിങ്ങൾക്ക് അടുത്ത് ലഭ്യം',
    trusted: 'വിശ്വസനീയ വിൽപ്പനക്കാർ',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    call: 'വിളിക്കുക',
    chat: 'ചാറ്റ് ചെയ്യുക',
    transport: 'ഗതാഗതം വേണോ?',
    addInventory: 'വിൽക്കുക',
    publish: 'പ്രസിദ്ധീകരിക്കുക',
    variety: 'ഇനം',
    quantity: 'അളവ്',
    price: 'വില',
    age: 'പ്രായം',
    location: 'നിലവിലെ സ്ഥലം',
    noOrders: 'ഓർഡറുകൾ ഇല്ല',
    noOrdersDesc: 'നിങ്ങളുടെ സമീപകാല വാങ്ങലുകളും വിൽപ്പനകളും ഇവിടെ കാണിക്കും.',
    startShopping: 'മാർക്കറ്റ് കാണുക',
    unitsLabel: 'നഗ',
    verifiedChoice: 'സ്ഥിരീകരിച്ച തിരഞ്ഞെടുപ്പ്',
    itemDetails: 'ഇനം വിശദാംശം',
    qualityVerified: 'ഗുണനിലവാരം സ്ഥിരീകരിച്ചു',
    selfPickup: 'നേരിട്ട് എടുക്കുക',
    requestTransport: 'ഗതാഗത സഹായം ആവശ്യപ്പെടുക',
    messages: 'സന്ദേശങ്ങൾ',
    sendEnquiry: 'അന്വേഷണം അയക്കുക',
    enquirySent: 'അന്വേഷണം അയച്ചു!',
    listingLocation: 'സ്ഥലം',
    viewMap: 'ഭൂപടം കാണുക',
    comingSoon: 'ഉടൻ വരുന്നു',
    comingSoonDesc: 'ഗതാഗത ബുക്കിംഗ് ഉടൻ ലഭ്യമാകും.',
    sellerProfile: 'വിൽപ്പനക്കാരൻ പ്രൊഫൈൽ',
    daysOnApp: 'App-ൽ ദിവസങ്ങൾ',
    itemsSold: 'വിറ്റ ഇനങ്ങൾ',
    otherListings: 'മറ്റ് ലിസ്റ്റിംഗ്',
    contactSeller: 'വിൽപ്പനക്കാരനെ ബന്ധപ്പെടുക',
    noMessages: 'സന്ദേശങ്ങൾ ഇല്ല',
    noMessagesDesc: 'സംഭാഷണം ആരംഭിക്കാൻ അന്വേഷണം അയക്കുക.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `നമസ്കാരം, Swaseva-ൽ നിങ്ങളുടെ ${productName} (₹${price}/${unit}) കണ്ടു. കൂടുതൽ വിവരങ്ങൾ ദയവായി അറിയിക്കൂ.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `നമസ്കാരം, Swaseva-ൽ നിങ്ങളുടെ ${productName} (₹${price}/${unit}) കണ്ടു. കൂടുതൽ വിവരങ്ങൾ ദയവായി അറിയിക്കൂ.`,
    cancel: 'റദ്ദ്', apply: 'പ്രയോഗിക്കുക', reset: 'റീസെറ്റ്', loading: 'ലോഡ്…',
    newsImpact: 'വാർത്ത & സ്വാധീനം', newsDesc: 'കൃഷി വാർത്തകൾ, MSP',
    nearbyShops: 'അടുത്ത കടകൾ', seeAll: 'എല്ലാം →', freshListings: 'പുതിയ ലിസ്റ്റിംഗ്',
    allIndia: 'ഇന്ത്യ മുഴുവൻ', all: 'എല്ലാം', agriInputs: 'കൃഷി വസ്തുക്കൾ',
    noProducts: 'ഉൽപ്പന്നങ്ങൾ ഇല്ല', fromOtherAreas: 'മറ്റ് പ്രദേശങ്ങളിൽ നിന്ന്',
    compareCount: (n: number) => `${n} താരതമ്യം`,
    filterSort: 'ഫിൽട്ടർ', sortBy: 'ക്രമം', newest: 'പുതിയത്',
    priceLow: 'കുറഞ്ഞ വില', priceHigh: 'കൂടിയ വില', priceRange: 'വില (₹)',
    min: 'ഏറ്റവും കുറവ്', max: 'ഏറ്റവും കൂടുതൽ',
    farmLocation: 'കൃഷിയിടം', tapMapDrag: 'മാപ്പിൽ ടാപ്പ് ചെയ്യുക',
    gettingAddress: 'വിലാസം…', tapMapSelect: 'മാപ്പ് ടാപ്പ്',
    confirmLocation: 'സ്ഥലം ഉറപ്പ്', published: 'പ്രസിദ്ധീകരിച്ചു!', newListing: 'പുതിയ ലിസ്റ്റ്',
    stepOf: (n: number) => `ഘട്ടം ${n} / 3`,
    chooseCategory: 'വിഭാഗം', photosVideos: 'ഫോട്ടോ / വീഡിയോ', addMore: 'കൂടുതൽ',
    priceUnit: 'വില യൂണിറ്റ്', stockQty: 'സ്റ്റോക്ക്', stockUnit: 'സ്റ്റോക്ക് യൂണിറ്റ്',
    productLocation: 'സ്ഥലം', pickLocation: 'മാപ്പ് ടാപ്പ്',
    mobileNumber: 'മൊബൈൽ', nextStep: 'അടുത്ത്', trustBadge: 'വിശ്വാസ ബാഡ്ജ്',
    identityUploaded: 'തിരിച്ചറിയൽ അ.', verifiedBadgeWill: 'Verified ബാഡ്ജ് കിട്ടും',
    uploadIdentity: 'തിരിച്ചറിയൽ അ.', description: 'വിവരണം', descriptionHint: 'ഗുണനിലവാരം…',
    newBtn: 'പുതിയത്', active: 'സജീവം', views: 'കാഴ്ചകൾ', leads: 'ലീഡ്',
    activeListings: (n: number) => `${n} സജീവ ലിസ്റ്റ്`,
    dukaanPortal: 'കട പോർട്ടൽ', manageShop: 'ഓർഡർ, ഇൻ.',
    noListings: 'ലിസ്റ്റ് ഇല്ല', sold: 'വിറ്റു', avail: 'ലഭ്യ.',
    editListing: 'തിരുത്തുക', preview: 'മുൻകാഴ്ച', delete: 'നീക്കുക',
    deleteConfirm: 'ലിസ്റ്റ് നീക്കണോ?', undo: 'പഴയതാക്കുക', listingDeleted: 'ലിസ്റ്റ് നീക്കി',
    becomeDukandaar: 'കടക്കാരൻ ആകുക', becomeShopkeeper: 'കടക്കാരൻ ആകുക →',
    buyerEnquiries: 'വാങ്ങുന്നവരുടെ ചോദ്യം', reply: 'മറുപടി', edit: 'തിരുത്ത്', availableQty: 'ലഭ്യ.',
    accountSettings: 'അക്കൗണ്ട് ക്രമീകരണം', personalInfo: 'വ്യക്തിഗതം', fullName: 'പേര്',
    languageLabel: 'ഭാഷ', changePassword: 'പാസ്‌വേഡ് മാറ്റം',
    currentPwd: 'പഴയ പ.', newPwd: 'പുതിയ പ.',
    minChars: 'കുറഞ്ഞത് 8 അക്ഷരം', saved: 'സൂക്ഷിച്ചു!', saveChanges: 'മാറ്റം സൂക്ഷിക്കുക',
    notifications: 'അറിയിപ്പുകൾ', alerts: 'മുന്നറിയിപ്പ്', channels: 'ചാനൽ',
    aadhaarCard: 'ആധാർ', identityVerification: 'തിരിച്ചറിയൽ',
    panCard: 'PAN', taxId: 'നികുതി', bankAccount: 'ബാങ്ക്',
    linkPayments: 'പേമെന്റ് ലിങ്ക്', accountNumber: 'അ.നം.', ifscCode: 'IFSC',
    linkAccount: 'അ. ലിങ്ക്', farmDetails: 'കൃഷി വിവരം', farmerIdentity: 'കർഷക തിരിച്ചറിയൽ',
    landArea: 'ഭൂമി (ഏക്കർ)', satbaraNumber: '7/12 നം.',
    uploadSatbara: '7/12 ഫോട്ടോ', submitReview: 'അവലോകനം',
    kycVerification: 'KYC', completion: 'പൂർത്തി',
    complete: '✓ പൂർത്തി', locked: '🔒 ലോക്ക്',
    helpSupport: 'സഹായം', rateApp: 'റേറ്റ് ചെയ്യുക',
    rateDesc: 'നിങ്ങളുടെ അഭിപ്രായം', faq: 'FAQ',
    callUs: 'വിളി', chatNow: 'ചാറ്റ്', emailUs: 'ഇമെയിൽ',
    shopRegistration: 'കട രജിസ്ട്രേഷൻ', premiumFarmer: 'പ്രീമിയം കർഷകൻ', myDukaan: 'എന്റെ കട',
    signOut: 'സൈൻ ഔട്ട്', signOutConfirm: 'സൈൻ ഔട്ട്?', signOutDesc: 'വീണ്ടും ലോഗിൻ ചെയ്യണം',
    verifiedStatus: 'സ്ഥിരീകരിച്ചു · 12 ജ. 2025',
    listingsLabel: 'ലിസ്റ്റ്', ratingLabel: 'റേറ്റിംഗ്', salesLabel: 'വിൽപ്പന',
    totalAmount: 'ആകെ', tracking: 'ട്രാക്കിംഗ്',
    sellerLabel: 'വിൽക്കുന്നവർ', buyerLabel: 'വാങ്ങുന്നവർ', priceBreakdown: 'വില',
    itemTotal: 'ഇനം', transportCost: 'ഗതാഗതം', paymentLabel: 'പേമെന്റ്',
    grandTotal: 'ആകെ', swaSevaProtected: 'Swaseva സുരക്ഷ',
    myTransactions: 'ഇടപാടുകൾ', purchased: '🛒 വാങ്ങി', soldTab: '🌾 വിറ്റു',
    ordersLabel: 'ഓർഡർ', spent: 'ചെലവ്', earned: 'വരുമാനം',
    swasevaLogistics: 'Swaseva ലൊജി.',
  },
};

export function getTranslations(lang: Language): typeof TRANSLATIONS.en {
  return (TRANSLATIONS as Record<string, typeof TRANSLATIONS.en>)[lang as string] ?? TRANSLATIONS.en;
}

export const PRICE_UNITS = [
  { value: 'kg',      label: 'per kg',      labelMr: 'प्रति किलो'      },
  { value: 'gram',    label: 'per 100g',    labelMr: 'प्रति १०० ग्रॅम'  },
  { value: 'quintal', label: 'per quintal', labelMr: 'प्रति क्विंटल'    },
  { value: 'tonne',   label: 'per tonne',   labelMr: 'प्रति टन'         },
  { value: 'dozen',   label: 'per dozen',   labelMr: 'प्रति डझन'        },
  { value: 'piece',   label: 'per piece',   labelMr: 'प्रति नग'         },
  { value: 'litre',   label: 'per litre',   labelMr: 'प्रति लिटर'       },
  { value: 'bundle',  label: 'per bundle',  labelMr: 'प्रति जुडी'       },
  { value: 'bag',     label: 'per bag',     labelMr: 'प्रति बोरे'       },
  { value: 'box',     label: 'per box',     labelMr: 'प्रति पेटी'       },
  { value: 'packet',  label: 'per packet',  labelMr: 'प्रति पॅकेट'      },
];

export const MOCK_SHOP_PROFILES: (ShopProfile & { shopkeeperId: string; shopNameMr: string; location: string; distance: string })[] = [
  {
    shopkeeperId: 'shop_001',
    shopName: 'Ganesh Krishi Seva Kendra',
    shopNameMr: 'गणेश कृषी सेवा केंद्र',
    location: 'Pune, Maharashtra',
    distance: '0.3 km',
    exteriorPhotoUri: 'https://images.unsplash.com/photo-1604719312566-8912e9c8a213?w=400',
    interiorPhotoUri: '',
    verificationStatus: 'pending' as const,
    gstOrLicense: 'GSTIN27AAACG1234A1ZD',
  },
  {
    shopkeeperId: 'shop_002',
    shopName: 'Shivaji Agro Stores',
    shopNameMr: 'शिवाजी अॅग्रो स्टोर्स',
    location: 'Nashik, Maharashtra',
    distance: '1.1 km',
    exteriorPhotoUri: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400',
    interiorPhotoUri: '',
    verificationStatus: 'pending' as const,
    gstOrLicense: 'LIC-PES-MH-2023-00142',
  },
  {
    shopkeeperId: 'shop_003',
    shopName: 'Mahalaxmi Seed House',
    shopNameMr: 'महालक्ष्मी सीड हाऊस',
    location: 'Aurangabad, Maharashtra',
    distance: '2.4 km',
    exteriorPhotoUri: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400',
    interiorPhotoUri: '',
    verificationStatus: 'pending' as const,
    gstOrLicense: 'GSTIN27BBBCM5678B2ZE',
  },
];

export const MOCK_SHOP_ITEMS: ShopItem[] = [
  { id: 'si_001', shopkeeperId: 'shop_001', name: 'Hybrid Tomato Seeds', nameMr: 'हायब्रिड टोमॅटो बियाणे', category: 'seeds', price: 280, unit: 'packet', stockQty: 45, stockThreshold: 10, description: '50g packet, disease resistant variety', descriptionMr: '50 ग्रॅम पॅकेट, रोगप्रतिकारक जात', imageUris: ['https://images.unsplash.com/photo-1592925741908-3c60d3a4a8c3?w=400'], brand: 'Syngenta', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_002', shopkeeperId: 'shop_001', name: 'NPK Fertilizer 19:19:19', nameMr: 'NPK खत 19:19:19', category: 'fertilizer', price: 1150, unit: 'bag', stockQty: 8, stockThreshold: 5, description: 'Water soluble complex fertilizer', descriptionMr: 'पाण्यात विरघळणारे संयुक्त खत', imageUris: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'], brand: 'Iffco', expiryDate: '2027-03-31', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_003', shopkeeperId: 'shop_002', name: 'Chlorpyrifos 20% EC', nameMr: 'क्लोरपायरीफॉस 20% EC', category: 'pesticide', price: 420, unit: 'litre', stockQty: 3, stockThreshold: 5, description: 'Broad spectrum insecticide', descriptionMr: 'व्यापक स्पेक्ट्रम कीटकनाशक', imageUris: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=400'], brand: 'Coromandel', expiryDate: '2026-12-31', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_004', shopkeeperId: 'shop_002', name: 'Hand Sprayer 16L', nameMr: 'हँड स्प्रेयर 16L', category: 'tools', price: 1850, unit: 'piece', stockQty: 12, stockThreshold: 3, description: 'Knapsack pressure sprayer', descriptionMr: 'नॅपसॅक प्रेशर स्प्रेयर', imageUris: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400'], isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_005', shopkeeperId: 'shop_003', name: 'Cotton Seed BG-II', nameMr: 'कापूस बियाणे BG-II', category: 'seeds', price: 920, unit: 'packet', stockQty: 30, stockThreshold: 8, description: 'Bt cotton high yield variety', descriptionMr: 'बीटी कापूस उच्च उत्पादन जात', imageUris: ['https://images.unsplash.com/photo-1573848933048-bba9a57b5bca?w=400'], brand: 'Mahyco', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_006', shopkeeperId: 'shop_003', name: 'Animal Feed Pellets', nameMr: 'पशुखाद्य गोळ्या', category: 'feed', price: 650, unit: 'bag', stockQty: 20, stockThreshold: 5, description: 'Balanced nutrition cattle feed', descriptionMr: 'संतुलित पोषण गोमांस खाद्य', imageUris: ['https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=400'], brand: 'Godrej Agrovet', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
];
