
import { Product, Seller, Category } from './types';

export const COLORS = {
  primary: '#2D5A27', // Forest Green
  secondary: '#6B4423', // Earth Brown
  accent: '#F97316', // Vibrant Orange
  background: '#F9FBF9',
};

export const SELLERS: Seller[] = [
  { id: 's1', name: 'Ramachandra Nursery', rating: 4.8, isVerified: true, distance: '4.2 km', phone: '+919876543210', location: 'Near Old Toll Gate, Pune' },
  { id: 's2', name: 'Krishi Seva Center', rating: 4.5, isVerified: true, distance: '8.5 km', phone: '+919876543211', location: 'Main Market, Baramati' },
  { id: 's3', name: 'Gajanan Seeds', rating: 3.9, isVerified: false, distance: '12.0 km', phone: '+919876543212', location: 'Satara Road' },
  { id: 's4', name: 'Vitthal Agro Inputs', rating: 4.6, isVerified: true, distance: '6.8 km', phone: '+919876543213', location: 'APMC Yard, Solapur' },
  { id: 's5', name: 'Sahyadri Farm Fresh', rating: 4.3, isVerified: true, distance: '15.2 km', phone: '+919876543214', location: 'Nashik–Pune Highway, Igatpuri' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sugarcane Saplings',
    nameMr: 'उसाची रोपे',
    category: 'Saplings',
    variety: 'CO 86032',
    varietyMr: 'सीओ ८६०३२',
    price: 3.5,
    unit: 'sapling',
    unitMr: 'रोप',
    quantity: 5000,
    age: '45 days',
    ageMr: '४५ दिवस',
    imageUrl: '/images/sugarcane-saplings.webp',
    sellerId: 's1',
    harvestDate: '2024-05-15',
    description: 'High-yield variety, disease resistant, and ready for planting. Grown under controlled environment.',
    descriptionMr: 'जास्त उत्पन्न देणारी जात, रोगप्रतिकारक आणि लागवडीसाठी तयार. नियंत्रित वातावरणात वाढवलेले.',
    mspPrice: 3.0,
  },
  {
    id: 'p2',
    name: 'Hybrid Tomato Seeds',
    nameMr: 'हायब्रीड टोमॅटो बियाणे',
    category: 'Seeds',
    variety: 'Abhinav',
    varietyMr: 'अभिनव',
    price: 450,
    unit: 'pack (50g)',
    unitMr: 'पॅक (५० ग्रॅम)',
    quantity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=800&auto=format&fit=crop',
    sellerId: 's2',
    description: 'F1 Hybrid Tomato seeds with excellent shelf life and firm fruit texture.',
    descriptionMr: 'उत्कृष्ट शेल्फ लाइफ आणि टणक फळांचा पोत असलेले F1 हायब्रीड टोमॅटो बियाणे.',
    mspPrice: 500,
  },
  {
    id: 'p3',
    name: 'NPK 19-19-19 Fertilizer',
    nameMr: 'NPK १९-१९-१९ खत',
    category: 'Fertilizer',
    variety: 'Water Soluble',
    varietyMr: 'पाण्यात विरघळणारे',
    price: 120,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 500,
    imageUrl: '/images/npk-19-19-19.webp',
    sellerId: 's2',
    description: 'Premium quality balanced NPK fertilizer for all crops.',
    descriptionMr: 'सर्व पिकांसाठी प्रीमियम दर्जाचे संतुलित NPK खत.',
  },
  {
    id: 'p5',
    name: 'Soybean (JS 335)',
    nameMr: 'सोयाबीन (जेएस ३३५)',
    category: 'Seeds',
    variety: 'JS 335',
    varietyMr: 'जेएस ३३५',
    price: 85,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 800,
    imageUrl: '/images/soybean.webp',
    sellerId: 's4',
    harvestDate: '2025-10-20',
    description: 'High-germination JS 335 soybean seeds. Drought-tolerant, ideal for Vidarbha and Marathwada regions.',
    descriptionMr: 'जास्त उगवण शक्तीचे जेएस ३३५ सोयाबीन बियाणे. दुष्काळ-सहिष्णु, विदर्भ आणि मराठवाड्यासाठी आदर्श.',
    mspPrice: 80,
  },
  {
    id: 'p6',
    name: 'Onion (Nasik Red)',
    nameMr: 'कांदा (नाशिक लाल)',
    category: 'Vegetables',
    variety: 'Nasik Red',
    varietyMr: 'नाशिक लाल',
    price: 32,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?q=80&w=800&auto=format&fit=crop',
    sellerId: 's5',
    harvestDate: '2025-04-01',
    description: 'Premium Nasik Red onions. Low moisture content, long shelf life, export-quality grading.',
    descriptionMr: 'उत्कृष्ट नाशिक लाल कांदे. कमी आर्द्रता, दीर्घ साठवण क्षमता, निर्यात दर्जाचे ग्रेडिंग.',
    mspPrice: 28,
  },
  {
    id: 'p7',
    name: 'Drip Irrigation Kit',
    nameMr: 'ठिबक सिंचन संच',
    category: 'Tools',
    variety: '2-Acre Set',
    varietyMr: '२ एकर संच',
    price: 12500,
    unit: 'set',
    unitMr: 'संच',
    quantity: 15,
    imageUrl: '/images/drip_irrigation_kit.jpg',
    sellerId: 's4',
    description: 'Complete drip irrigation kit for 2 acres. Includes inline drippers, mainline pipe, header pipe, and fittings. Subsidy eligible.',
    descriptionMr: '२ एकरसाठी संपूर्ण ठिबक सिंचन संच. इनलाइन ड्रिपर्स, मुख्य पाइप, हेडर पाइप आणि फिटिंगसह. अनुदानासाठी पात्र.',
    mspPrice: 12000,
  },
  {
    id: 'p4',
    name: 'Mango Graft (Kesar)',
    nameMr: 'केसर आंब्याची कलमे',
    category: 'Saplings',
    variety: 'Kesar',
    varietyMr: 'केसर',
    price: 180,
    unit: 'plant',
    unitMr: 'कलम',
    quantity: 250,
    age: '1 year',
    ageMr: '१ वर्ष',
    imageUrl: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?q=80&w=800&auto=format&fit=crop',
    sellerId: 's1',
    description: 'Healthy 1-year-old Kesar mango grafts. Guaranteed survival rate.',
    descriptionMr: 'निरोगी १ वर्ष जुन्या केसर आंब्याची कलमे. जगण्याची खात्रीशीर टक्केवारी.',
    mspPrice: 150,
  },
];

export const CATEGORIES: Category[] = [
  { id: 'c1', name: 'Seeds', nameMr: 'बियाणे', icon: '🌱' },
  { id: 'c2', name: 'Saplings', nameMr: 'रोपे', icon: '🌳' },
  { id: 'c3', name: 'Fertilizer', nameMr: 'खते', icon: '🧴' },
  { id: 'c4', name: 'Pesticides', nameMr: 'कीटकनाशके', icon: '🧪' },
  { id: 'c5', name: 'Tools', nameMr: 'अवजारे', icon: '🛠️' },
];

export const TRANSLATIONS = {
  en: {
    home: 'Market',
    sell: 'Sell',
    listings: 'Listings',
    orders: 'Orders',
    profile: 'Profile',
    searchPlaceholder: 'Search seeds, saplings...',
    nearYou: 'Available Near You',
    trusted: 'Trusted Sellers',
    viewDetails: 'View Details',
    call: 'Call Seller',
    chat: 'Chat on App',
    transport: 'Need Transport?',
    addInventory: 'Add New Item',
    publish: 'Publish Listing',
    variety: 'Variety',
    quantity: 'Quantity',
    price: 'Price',
    age: 'Age',
    location: 'Current Location',
    noOrders: 'No Orders Yet',
    noOrdersDesc: 'Your recent purchases and sales will appear here.',
    startShopping: 'Browse Market',
    unitsLabel: 'UNITS',
    verifiedChoice: 'Verified Choice',
    itemDetails: 'Item Details',
    qualityVerified: 'Quality Verified',
    selfPickup: 'Self-Pickup',
    requestTransport: 'Request Transport Help'
  },
  mr: {
    home: 'बाजार',
    sell: 'विका',
    listings: 'लिस्टिंग',
    orders: 'ऑर्डर्स',
    profile: 'प्रोफाईल',
    searchPlaceholder: 'बियाणे, रोपे शोधा...',
    nearYou: 'तुमच्या जवळ उपलब्ध',
    trusted: 'विश्वासार्ह विक्रेते',
    viewDetails: 'माहिती पहा',
    call: 'संपर्क करा',
    chat: 'चॅट करा',
    transport: 'वाहतूक हवी आहे?',
    addInventory: 'नवीन वस्तू जोडा',
    publish: 'प्रकाशित करा',
    variety: 'वाण / जात',
    quantity: 'प्रमाण',
    price: 'किंमत',
    age: 'कालावधी',
    location: 'सध्याचे ठिकाण',
    noOrders: 'अद्याप ऑर्डर्स नाहीत',
    noOrdersDesc: 'तुमच्या अलीकडील खरेदी आणि विक्री येथे दिसतील.',
    startShopping: 'बाजार पहा',
    unitsLabel: 'नग/प्रमाण',
    verifiedChoice: 'सत्यापित निवड',
    itemDetails: 'वस्तूचा तपशील',
    qualityVerified: 'गुणवत्ता सत्यापित',
    selfPickup: 'स्वतः उचलणे',
    requestTransport: 'वाहतुकीसाठी मदत मागा'
  }
};
