
import { Product, Seller, Category, Language, ShopProfile, ShopItem } from './types';

export const COLORS = {
  primary: '#2D5A27', // Forest Green
  secondary: '#6B4423', // Earth Brown
  accent: '#F97316', // Vibrant Orange
  background: '#F9FBF9',
};

export const SELLERS: Seller[] = [
  {
    id: 's1', name: 'Ramachandra Nursery', rating: 4.8, isVerified: true,
    distance: '4.2 km', phone: '+919876543210', location: 'Near Old Toll Gate, Pune',
    speciality: ['Saplings', 'Grafting', 'Fruit Trees'],
    daysOnApp: 312, totalSold: 4800,
    bio: 'Third-generation nursery specialising in grafted saplings and fruit trees. All plants are certified disease-free.',
    bioMr: 'तीन पिढ्यांचे नर्सरी, कलमे आणि फळझाडांमध्ये विशेष. सर्व रोपे रोगमुक्त प्रमाणित.',
    avatarColor: '#1A4D1A',
  },
  {
    id: 's2', name: 'Krishi Seva Center', rating: 4.5, isVerified: true,
    distance: '8.5 km', phone: '+919876543211', location: 'Main Market, Baramati',
    speciality: ['Seeds', 'Fertilizers', 'Agri Inputs'],
    daysOnApp: 198, totalSold: 2300,
    bio: 'Your one-stop agri-input center in Baramati. Government-empanelled distributor for premium seed brands.',
    bioMr: 'बारामतीमधील तुमचे संपूर्ण कृषी निविष्ठा केंद्र. सरकार मान्यताप्राप्त वितरक.',
    avatarColor: '#1A3D4D',
  },
  {
    id: 's3', name: 'Gajanan Seeds', rating: 3.9, isVerified: false,
    distance: '12.0 km', phone: '+919876543212', location: 'Satara Road',
    speciality: ['Seeds', 'Grains'],
    daysOnApp: 87, totalSold: 540,
    bio: 'Local seed trader with 10+ years of experience in Kharif and Rabi crop varieties.',
    bioMr: 'खरीप आणि रब्बी पिकांच्या जातींमध्ये १०+ वर्षांचा अनुभव असलेला स्थानिक बियाणे व्यापारी.',
    avatarColor: '#4D3A1A',
  },
  {
    id: 's4', name: 'Vitthal Agro Inputs', rating: 4.6, isVerified: true,
    distance: '6.8 km', phone: '+919876543213', location: 'APMC Yard, Solapur',
    speciality: ['Fertilizers', 'Drip Irrigation', 'Tools'],
    daysOnApp: 445, totalSold: 6200,
    bio: 'Solapur\'s leading agro input supplier. Authorized dealer for drip irrigation systems. Subsidy processing support available.',
    bioMr: 'सोलापूरचे अग्रगण्य कृषी निविष्ठा पुरवठादार. ठिबक सिंचन प्रणालीचे अधिकृत डीलर.',
    avatarColor: '#4D1A1A',
  },
  {
    id: 's5', name: 'Sahyadri Farm Fresh', rating: 4.3, isVerified: true,
    distance: '15.2 km', phone: '+919876543214', location: 'Nashik–Pune Highway, Igatpuri',
    speciality: ['Vegetables', 'Onion', 'Export Quality'],
    daysOnApp: 267, totalSold: 3900,
    bio: 'Farm-to-market fresh produce from the Sahyadri belt. Export-grade grading and packing available.',
    bioMr: 'सह्याद्री पट्ट्यातून थेट शेतातून बाजारात. निर्यात दर्जाचे ग्रेडिंग आणि पॅकिंग उपलब्ध.',
    avatarColor: '#1A4D3A',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Sugarcane Saplings',
    nameMr: 'उसाची रोपे',
    category: 'Saplings',
    variety: 'CO 86032',
    varietyMr: 'सीओ ८६०३२',
    price: 3.5,
    unit: 'sapling',
    unitMr: 'रोप',
    quantity: 5000,
    age: '45 days',
    ageMr: '४५ दिवस',
    imageUrl: '/images/sugarcane-saplings.webp',
    sellerId: 's1',
    harvestDate: '2024-05-15',
    description: 'High-yield variety, disease resistant, and ready for planting. Grown under controlled environment.',
    descriptionMr: 'जास्त उत्पन्न देणारी जात, रोगप्रतिकारक आणि लागवडीसाठी तयार. नियंत्रित वातावरणात वाढवलेले.',
    mspPrice: 3.0,
  },
  {
    id: 'p2',
    name: 'Hybrid Tomato Seeds',
    nameMr: 'हायब्रीड टोमॅटो बियाणे',
    category: 'Seeds',
    variety: 'Abhinav',
    varietyMr: 'अभिनव',
    price: 450,
    unit: 'pack (50g)',
    unitMr: 'पॅक (५० ग्रॅम)',
    quantity: 100,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=800&auto=format&fit=crop',
    sellerId: 's2',
    description: 'F1 Hybrid Tomato seeds with excellent shelf life and firm fruit texture.',
    descriptionMr: 'उत्कृष्ट शेल्फ लाइफ आणि टणक फळांचा पोत असलेले F1 हायब्रीड टोमॅटो बियाणे.',
    mspPrice: 500,
  },
  {
    id: 'p3',
    name: 'NPK 19-19-19 Fertilizer',
    nameMr: 'NPK १९-१९-१९ खत',
    category: 'Fertilizer',
    variety: 'Water Soluble',
    varietyMr: 'पाण्यात विरघळणारे',
    price: 120,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 500,
    imageUrl: '/images/npk-19-19-19.webp',
    sellerId: 's2',
    description: 'Premium quality balanced NPK fertilizer for all crops.',
    descriptionMr: 'सर्व पिकांसाठी प्रीमियम दर्जाचे संतुलित NPK खत.',
  },
  {
    id: 'p5',
    name: 'Soybean (JS 335)',
    nameMr: 'सोयाबीन (जेएस ३३५)',
    category: 'Seeds',
    variety: 'JS 335',
    varietyMr: 'जेएस ३३५',
    price: 85,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 800,
    imageUrl: '/images/soybean.webp',
    sellerId: 's4',
    harvestDate: '2025-10-20',
    description: 'High-germination JS 335 soybean seeds. Drought-tolerant, ideal for Vidarbha and Marathwada regions.',
    descriptionMr: 'जास्त उगवण शक्तीचे जेएस ३३५ सोयाबीन बियाणे. दुष्काळ-सहिष्णु, विदर्भ आणि मराठवाड्यासाठी आदर्श.',
    mspPrice: 80,
  },
  {
    id: 'p6',
    name: 'Onion (Nasik Red)',
    nameMr: 'कांदा (नाशिक लाल)',
    category: 'Vegetables',
    variety: 'Nasik Red',
    varietyMr: 'नाशिक लाल',
    price: 32,
    unit: 'kg',
    unitMr: 'किलो',
    quantity: 2000,
    imageUrl: 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?q=80&w=800&auto=format&fit=crop',
    sellerId: 's5',
    harvestDate: '2025-04-01',
    description: 'Premium Nasik Red onions. Low moisture content, long shelf life, export-quality grading.',
    descriptionMr: 'उत्कृष्ट नाशिक लाल कांदे. कमी आर्द्रता, दीर्घ साठवण क्षमता, निर्यात दर्जाचे ग्रेडिंग.',
    mspPrice: 28,
  },
  {
    id: 'p7',
    name: 'Drip Irrigation Kit',
    nameMr: 'ठिबक सिंचन संच',
    category: 'Tools',
    variety: '2-Acre Set',
    varietyMr: '२ एकर संच',
    price: 12500,
    unit: 'set',
    unitMr: 'संच',
    quantity: 15,
    imageUrl: '/images/drip_irrigation_kit.jpg',
    sellerId: 's4',
    description: 'Complete drip irrigation kit for 2 acres. Includes inline drippers, mainline pipe, header pipe, and fittings. Subsidy eligible.',
    descriptionMr: '२ एकरसाठी संपूर्ण ठिबक सिंचन संच. इनलाइन ड्रिपर्स, मुख्य पाइप, हेडर पाइप आणि फिटिंगसह. अनुदानासाठी पात्र.',
    mspPrice: 12000,
  },
  {
    id: 'p4',
    name: 'Mango Graft (Kesar)',
    nameMr: 'केसर आंब्याची कलमे',
    category: 'Saplings',
    variety: 'Kesar',
    varietyMr: 'केसर',
    price: 180,
    unit: 'plant',
    unitMr: 'कलम',
    quantity: 250,
    age: '1 year',
    ageMr: '१ वर्ष',
    imageUrl: 'https://images.unsplash.com/photo-1591073113125-e46713c829ed?q=80&w=800&auto=format&fit=crop',
    sellerId: 's1',
    description: 'Healthy 1-year-old Kesar mango grafts. Guaranteed survival rate.',
    descriptionMr: 'निरोगी १ वर्ष जुन्या केसर आंब्याची कलमे. जगण्याची खात्रीशीर टक्केवारी.',
    mspPrice: 150,
  },
];

export const CATEGORIES: Category[] = [
  { id: 'c1', name: 'Seeds', nameMr: 'बियाणे', icon: '🌱' },
  { id: 'c2', name: 'Saplings', nameMr: 'रोपे', icon: '🌳' },
  { id: 'c3', name: 'Fertilizer', nameMr: 'खते', icon: '🧴' },
  { id: 'c4', name: 'Pesticides', nameMr: 'कीटकनाशके', icon: '🧪' },
  { id: 'c5', name: 'Tools', nameMr: 'अवजारे', icon: '🛠️' },
];

export const TRANSLATIONS = {
  en: {
    home: 'Market',
    sell: 'Sell',
    listings: 'Listings',
    myShop: 'My Shop',
    orders: 'Orders',
    profile: 'Profile',
    searchPlaceholder: 'Search seeds, saplings...',
    nearYou: 'Available Near You',
    trusted: 'Trusted Sellers',
    viewDetails: 'View Details',
    call: 'Call Seller',
    chat: 'Chat on App',
    transport: 'Need Transport?',
    addInventory: 'Sell Your Stock',
    publish: 'Publish Listing',
    variety: 'Variety',
    quantity: 'Quantity',
    price: 'Price',
    age: 'Age',
    location: 'Current Location',
    noOrders: 'No Orders Yet',
    noOrdersDesc: 'Your recent purchases and sales will appear here.',
    startShopping: 'Browse Market',
    unitsLabel: 'UNITS',
    verifiedChoice: 'Verified Choice',
    itemDetails: 'Item Details',
    qualityVerified: 'Quality Verified',
    selfPickup: 'Self-Pickup',
    requestTransport: 'Request Transport Help',
    messages: 'Messages',
    sendEnquiry: 'Send Enquiry',
    enquirySent: 'Enquiry Sent!',
    listingLocation: 'Listing Location',
    viewMap: 'View Map',
    comingSoon: 'Coming Soon',
    comingSoonDesc: 'Transport booking will be available soon. We\'ll notify you!',
    sellerProfile: 'Seller Profile',
    daysOnApp: 'Days on App',
    itemsSold: 'Items Sold',
    otherListings: 'Other Listings',
    contactSeller: 'Contact Seller',
    noMessages: 'No Messages Yet',
    noMessagesDesc: 'Send an enquiry on any listing to start a conversation.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `Hi, I'm interested in your ${productName} listed at ₹${price}/${unit} on Swaseva. Please share more details.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `नमस्कार, मला Swaseva वर तुमचे ${productName} (₹${price}/${unit}) पाहिले. कृपया अधिक माहिती द्या.`,
  },
  mr: {
    home: 'बाजार',
    sell: 'विका',
    listings: 'लिस्टिंग',
    myShop: 'माझी दुकान',
    orders: 'ऑर्डर्स',
    profile: 'प्रोफाईल',
    searchPlaceholder: 'बियाणे, रोपे शोधा...',
    nearYou: 'तुमच्या जवळ उपलब्ध',
    trusted: 'विश्वासार्ह विक्रेते',
    viewDetails: 'माहिती पहा',
    call: 'संपर्क करा',
    chat: 'चॅट करा',
    transport: 'वाहतूक हवी आहे?',
    addInventory: 'माल विका',
    publish: 'प्रकाशित करा',
    variety: 'वाण / जात',
    quantity: 'प्रमाण',
    price: 'किंमत',
    age: 'कालावधी',
    location: 'सध्याचे ठिकाण',
    noOrders: 'अद्याप ऑर्डर्स नाहीत',
    noOrdersDesc: 'तुमच्या अलीकडील खरेदी आणि विक्री येथे दिसतील.',
    startShopping: 'बाजार पहा',
    unitsLabel: 'नग/प्रमाण',
    verifiedChoice: 'सत्यापित निवड',
    itemDetails: 'वस्तूचा तपशील',
    qualityVerified: 'गुणवत्ता सत्यापित',
    selfPickup: 'स्वतः उचलणे',
    requestTransport: 'वाहतुकीसाठी मदत मागा',
    messages: 'संदेश',
    sendEnquiry: 'चौकशी पाठवा',
    enquirySent: 'चौकशी पाठवली!',
    listingLocation: 'लिस्टिंग ठिकाण',
    viewMap: 'नकाशा पहा',
    comingSoon: 'लवकरच येत आहे',
    comingSoonDesc: 'वाहतूक बुकिंग लवकरच उपलब्ध होईल. आम्ही तुम्हाला सूचित करू!',
    sellerProfile: 'विक्रेता प्रोफाईल',
    daysOnApp: 'App वर दिवस',
    itemsSold: 'विकलेल्या वस्तू',
    otherListings: 'इतर लिस्टिंग',
    contactSeller: 'विक्रेत्याशी संपर्क',
    noMessages: 'अद्याप संदेश नाहीत',
    noMessagesDesc: 'संभाषण सुरू करण्यासाठी कोणत्याही लिस्टिंगवर चौकशी पाठवा.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `नमस्कार, मला Swaseva वर तुमचे ${productName} (₹${price}/${unit}) पाहिले. कृपया अधिक माहिती द्या.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `नमस्कार, मला Swaseva वर तुमचे ${productName} (₹${price}/${unit}) पाहिले. कृपया अधिक माहिती द्या.`,
  },
  hi: {
    home: 'बाज़ार',
    sell: 'माल बेचें',
    listings: 'लिस्टिंग',
    myShop: 'मेरी दुकान',
    orders: 'ऑर्डर',
    profile: 'प्रोफ़ाइल',
    searchPlaceholder: 'बीज, पौधे खोजें...',
    nearYou: 'आपके पास उपलब्ध',
    trusted: 'भरोसेमंद विक्रेता',
    viewDetails: 'विवरण देखें',
    call: 'कॉल करें',
    chat: 'चैट करें',
    transport: 'परिवहन चाहिए?',
    addInventory: 'माल बेचें',
    publish: 'सूची करें',
    variety: 'किस्म',
    quantity: 'मात्रा',
    price: 'मूल्य',
    age: 'आयु',
    location: 'वर्तमान स्थान',
    noOrders: 'कोई ऑर्डर नहीं',
    noOrdersDesc: 'आपकी हालिया खरीद और बिक्री यहाँ दिखेगी।',
    startShopping: 'बाज़ार देखें',
    unitsLabel: 'नग',
    verifiedChoice: 'सत्यापित विकल्प',
    itemDetails: 'वस्तु का विवरण',
    qualityVerified: 'गुणवत्ता सत्यापित',
    selfPickup: 'खुद उठाएं',
    requestTransport: 'परिवहन सहायता मांगें',
    messages: 'संदेश',
    sendEnquiry: 'पूछताछ भेजें',
    enquirySent: 'पूछताछ भेजी!',
    listingLocation: 'स्थान',
    viewMap: 'नक्शा देखें',
    comingSoon: 'जल्द आ रहा है',
    comingSoonDesc: 'परिवहन बुकिंग जल्द उपलब्ध होगी। हम आपको सूचित करेंगे!',
    sellerProfile: 'विक्रेता प्रोफ़ाइल',
    daysOnApp: 'ऐप पर दिन',
    itemsSold: 'बिकी वस्तुएं',
    otherListings: 'अन्य सूचियां',
    contactSeller: 'विक्रेता से संपर्क',
    noMessages: 'कोई संदेश नहीं',
    noMessagesDesc: 'बातचीत शुरू करने के लिए कोई पूछताछ भेजें।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `नमस्ते, Swaseva पर आपका ${productName} (₹${price}/${unit}) देखा। कृपया अधिक जानकारी दें।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `नमस्ते, Swaseva पर आपका ${productName} (₹${price}/${unit}) देखा। कृपया अधिक जानकारी दें।`,
  },
  gu: {
    home: 'બજાર',
    sell: 'માલ વેચો',
    listings: 'લિસ્ટિંગ',
    myShop: 'મારી દુકાન',
    orders: 'ઓર્ડર',
    profile: 'પ્રોફાઇલ',
    searchPlaceholder: 'બિયારણ, છોડ શોધો...',
    nearYou: 'તમારી નજીક ઉપલબ્ધ',
    trusted: 'વિશ્વસનીય વિક્રેતા',
    viewDetails: 'વિગત જુઓ',
    call: 'ફોન કરો',
    chat: 'ચેટ કરો',
    transport: 'વાહન જોઈએ?',
    addInventory: 'માલ વેચો',
    publish: 'પ્રકાશિત કરો',
    variety: 'જાત',
    quantity: 'જથ્થો',
    price: 'ભાવ',
    age: 'ઉંમર',
    location: 'વર્તમાન સ્થાન',
    noOrders: 'કોઈ ઓર્ડર નથી',
    noOrdersDesc: 'તમારી ખરીદી અને વેચાણ અહીં દેખાશે.',
    startShopping: 'બજાર જુઓ',
    unitsLabel: 'નંગ',
    verifiedChoice: 'ચકાસાયેલ પસંદગી',
    itemDetails: 'વસ્તુની વિગત',
    qualityVerified: 'ગુણવત્તા ચકાસાઈ',
    selfPickup: 'જાતે લઈ જાઓ',
    requestTransport: 'વાહન સહાય માગો',
    messages: 'સંદેશ',
    sendEnquiry: 'પૂછપરછ મોકલો',
    enquirySent: 'પૂછપરછ મોકલાઈ!',
    listingLocation: 'સ્થાન',
    viewMap: 'નકશો જુઓ',
    comingSoon: 'જલ્દ આવે છે',
    comingSoonDesc: 'વાહન બુકિંગ જલ્દ ઉપલબ્ધ થશે. અમે જાણ કરીશું!',
    sellerProfile: 'વિક્રેતા પ્રોફાઇલ',
    daysOnApp: 'App પર દિવસ',
    itemsSold: 'વેચાઈ ગઈ વસ્તુઓ',
    otherListings: 'અન્ય લિસ્ટિંગ',
    contactSeller: 'વિક્રેતા સાથે સંપર્ક',
    noMessages: 'કોઈ સંદેશ નથી',
    noMessagesDesc: 'વાર્તાલાપ શરૂ કરવા પૂછપરછ મોકલો.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `નમસ્તે, Swaseva પર તમારો ${productName} (₹${price}/${unit}) જોયો. વધુ માહિતી આપો.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `નમસ્તે, Swaseva પર તમારો ${productName} (₹${price}/${unit}) જોયો. વધુ માહિતી આપો.`,
  },
  te: {
    home: 'మార్కెట్',
    sell: 'అమ్మండి',
    listings: 'జాబితాలు',
    myShop: 'నా దుకాణం',
    orders: 'ఆర్డర్లు',
    profile: 'ప్రొఫైల్',
    searchPlaceholder: 'విత్తనాలు, మొక్కలు వెతకండి...',
    nearYou: 'మీ దగ్గర అందుబాటులో',
    trusted: 'నమ్మకమైన విక్రేతలు',
    viewDetails: 'వివరాలు చూడండి',
    call: 'కాల్ చేయండి',
    chat: 'చాట్ చేయండి',
    transport: 'రవాణా కావాలా?',
    addInventory: 'అమ్మండి',
    publish: 'ప్రచురించండి',
    variety: 'రకం',
    quantity: 'పరిమాణం',
    price: 'ధర',
    age: 'వయసు',
    location: 'ప్రస్తుత స్థానం',
    noOrders: 'ఆర్డర్లు లేవు',
    noOrdersDesc: 'మీ తాజా కొనుగోళ్లు మరియు అమ్మకాలు ఇక్కడ కనిపిస్తాయి.',
    startShopping: 'మార్కెట్ చూడండి',
    unitsLabel: 'నగ్',
    verifiedChoice: 'ధృవీకరించిన ఎంపిక',
    itemDetails: 'వస్తువు వివరాలు',
    qualityVerified: 'నాణ్యత ధృవీకరించబడింది',
    selfPickup: 'స్వయంగా తీసుకెళ్ళండి',
    requestTransport: 'రవాణా సహాయం కోరండి',
    messages: 'సందేశాలు',
    sendEnquiry: 'విచారణ పంపండి',
    enquirySent: 'విచారణ పంపబడింది!',
    listingLocation: 'స్థానం',
    viewMap: 'మ్యాప్ చూడండి',
    comingSoon: 'త్వరలో వస్తోంది',
    comingSoonDesc: 'రవాణా బుకింగ్ త్వరలో అందుబాటులో ఉంటుంది.',
    sellerProfile: 'విక్రేత ప్రొఫైల్',
    daysOnApp: 'యాప్‌లో రోజులు',
    itemsSold: 'అమ్మిన వస్తువులు',
    otherListings: 'ఇతర జాబితాలు',
    contactSeller: 'విక్రేతను సంప్రదించండి',
    noMessages: 'సందేశాలు లేవు',
    noMessagesDesc: 'సంభాషణ ప్రారంభించడానికి విచారణ పంపండి.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `నమస్కారం, Swaseva లో మీ ${productName} (₹${price}/${unit}) చూశాను. దయచేసి మరిన్ని వివరాలు పంపండి.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `నమస్కారం, Swaseva లో మీ ${productName} (₹${price}/${unit}) చూశాను. దయచేసి మరిన్ని వివరాలు పంపండి.`,
  },
  pa: {
    home: 'ਬਾਜ਼ਾਰ',
    sell: 'ਮਾਲ ਵੇਚੋ',
    listings: 'ਲਿਸਟਿੰਗ',
    myShop: 'ਮੇਰੀ ਦੁਕਾਨ',
    orders: 'ਆਰਡਰ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    searchPlaceholder: 'ਬੀਜ, ਬੂਟੇ ਲੱਭੋ...',
    nearYou: 'ਤੁਹਾਡੇ ਨੇੜੇ ਉਪਲਬਧ',
    trusted: 'ਭਰੋਸੇਯੋਗ ਵਿਕ੍ਰੇਤਾ',
    viewDetails: 'ਵੇਰਵਾ ਦੇਖੋ',
    call: 'ਕਾਲ ਕਰੋ',
    chat: 'ਚੈਟ ਕਰੋ',
    transport: 'ਆਵਾਜਾਈ ਚਾਹੀਦੀ ਹੈ?',
    addInventory: 'ਮਾਲ ਵੇਚੋ',
    publish: 'ਪ੍ਰਕਾਸ਼ਿਤ ਕਰੋ',
    variety: 'ਕਿਸਮ',
    quantity: 'ਮਾਤਰਾ',
    price: 'ਕੀਮਤ',
    age: 'ਉਮਰ',
    location: 'ਮੌਜੂਦਾ ਟਿਕਾਣਾ',
    noOrders: 'ਕੋਈ ਆਰਡਰ ਨਹੀਂ',
    noOrdersDesc: 'ਤੁਹਾਡੀਆਂ ਹਾਲੀਆ ਖਰੀਦਾਂ ਅਤੇ ਵਿਕਰੀ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।',
    startShopping: 'ਬਾਜ਼ਾਰ ਦੇਖੋ',
    unitsLabel: 'ਨੰਗ',
    verifiedChoice: 'ਪ੍ਰਮਾਣਿਤ ਵਿਕਲਪ',
    itemDetails: 'ਵਸਤੂ ਦਾ ਵੇਰਵਾ',
    qualityVerified: 'ਗੁਣਵੱਤਾ ਤਸਦੀਕ',
    selfPickup: 'ਖੁਦ ਲੈ ਜਾਓ',
    requestTransport: 'ਆਵਾਜਾਈ ਸਹਾਇਤਾ ਮੰਗੋ',
    messages: 'ਸੁਨੇਹੇ',
    sendEnquiry: 'ਪੁੱਛਗਿੱਛ ਭੇਜੋ',
    enquirySent: 'ਪੁੱਛਗਿੱਛ ਭੇਜੀ!',
    listingLocation: 'ਟਿਕਾਣਾ',
    viewMap: 'ਨਕਸ਼ਾ ਦੇਖੋ',
    comingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
    comingSoonDesc: 'ਟ੍ਰਾਂਸਪੋਰਟ ਬੁਕਿੰਗ ਜਲਦੀ ਉਪਲਬਧ ਹੋਵੇਗੀ।',
    sellerProfile: 'ਵਿਕ੍ਰੇਤਾ ਪ੍ਰੋਫਾਈਲ',
    daysOnApp: 'App ਤੇ ਦਿਨ',
    itemsSold: 'ਵਿਕੀਆਂ ਵਸਤੂਆਂ',
    otherListings: 'ਹੋਰ ਲਿਸਟਿੰਗ',
    contactSeller: 'ਵਿਕ੍ਰੇਤਾ ਨਾਲ ਸੰਪਰਕ',
    noMessages: 'ਕੋਈ ਸੁਨੇਹਾ ਨਹੀਂ',
    noMessagesDesc: 'ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਪੁੱਛਗਿੱਛ ਭੇਜੋ।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, Swaseva ਤੇ ਤੁਹਾਡਾ ${productName} (₹${price}/${unit}) ਦੇਖਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਜਾਣਕਾਰੀ ਦਿਓ।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, Swaseva ਤੇ ਤੁਹਾਡਾ ${productName} (₹${price}/${unit}) ਦੇਖਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਜਾਣਕਾਰੀ ਦਿਓ।`,
  },
  kn: {
    home: 'ಮಾರುಕಟ್ಟೆ',
    sell: 'ಮಾರಾಟ ಮಾಡಿ',
    listings: 'ಪಟ್ಟಿಗಳು',
    myShop: 'ನನ್ನ ಅಂಗಡಿ',
    orders: 'ಆದೇಶಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    searchPlaceholder: 'ಬೀಜಗಳು, ಸಸಿಗಳನ್ನು ಹುಡುಕಿ...',
    nearYou: 'ನಿಮ್ಮ ಹತ್ತಿರ ಲಭ್ಯ',
    trusted: 'ನಂಬಲರ್ಹ ಮಾರಾಟಗಾರರು',
    viewDetails: 'ವಿವರ ನೋಡಿ',
    call: 'ಕರೆ ಮಾಡಿ',
    chat: 'ಚಾಟ್ ಮಾಡಿ',
    transport: 'ಸಾರಿಗೆ ಬೇಕೇ?',
    addInventory: 'ಮಾರಾಟ ಮಾಡಿ',
    publish: 'ಪ್ರಕಟಿಸಿ',
    variety: 'ತಳಿ',
    quantity: 'ಪ್ರಮಾಣ',
    price: 'ಬೆಲೆ',
    age: 'ವಯಸ್ಸು',
    location: 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
    noOrders: 'ಯಾವುದೇ ಆದೇಶಗಳಿಲ್ಲ',
    noOrdersDesc: 'ನಿಮ್ಮ ಇತ್ತೀಚಿನ ಖರೀದಿ ಮತ್ತು ಮಾರಾಟ ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ.',
    startShopping: 'ಮಾರುಕಟ್ಟೆ ನೋಡಿ',
    unitsLabel: 'ನಗ',
    verifiedChoice: 'ಪರಿಶೀಲಿಸಿದ ಆಯ್ಕೆ',
    itemDetails: 'ವಸ್ತು ವಿವರ',
    qualityVerified: 'ಗುಣಮಟ್ಟ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    selfPickup: 'ಸ್ವಯಂ ತೆಗೆದುಕೊಳ್ಳಿ',
    requestTransport: 'ಸಾರಿಗೆ ಸಹಾಯ ಕೇಳಿ',
    messages: 'ಸಂದೇಶಗಳು',
    sendEnquiry: 'ವಿಚಾರಣೆ ಕಳುಹಿಸಿ',
    enquirySent: 'ವಿಚಾರಣೆ ಕಳುಹಿಸಲಾಗಿದೆ!',
    listingLocation: 'ಸ್ಥಳ',
    viewMap: 'ನಕ್ಷೆ ನೋಡಿ',
    comingSoon: 'ಶೀಘ್ರದಲ್ಲಿ ಬರಲಿದೆ',
    comingSoonDesc: 'ಸಾರಿಗೆ ಬುಕಿಂಗ್ ಶೀಘ್ರದಲ್ಲಿ ಲಭ್ಯವಾಗಲಿದೆ.',
    sellerProfile: 'ಮಾರಾಟಗಾರರ ಪ್ರೊಫೈಲ್',
    daysOnApp: 'App ನಲ್ಲಿ ದಿನಗಳು',
    itemsSold: 'ಮಾರಾಟವಾದ ವಸ್ತುಗಳು',
    otherListings: 'ಇತರ ಪಟ್ಟಿಗಳು',
    contactSeller: 'ಮಾರಾಟಗಾರರನ್ನು ಸಂಪರ್ಕಿಸಿ',
    noMessages: 'ಯಾವುದೇ ಸಂದೇಶಗಳಿಲ್ಲ',
    noMessagesDesc: 'ಸಂಭಾಷಣೆ ಪ್ರಾರಂಭಿಸಲು ವಿಚಾರಣೆ ಕಳುಹಿಸಿ.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `ನಮಸ್ಕಾರ, Swaseva ನಲ್ಲಿ ನಿಮ್ಮ ${productName} (₹${price}/${unit}) ನೋಡಿದೆ. ದಯವಿಟ್ಟು ಹೆಚ್ಚಿನ ವಿವರ ನೀಡಿ.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `ನಮಸ್ಕಾರ, Swaseva ನಲ್ಲಿ ನಿಮ್ಮ ${productName} (₹${price}/${unit}) ನೋಡಿದೆ. ದಯವಿಟ್ಟು ಹೆಚ್ಚಿನ ವಿವರ ನೀಡಿ.`,
  },
  ta: {
    home: 'சந்தை',
    sell: 'விற்கவும்',
    listings: 'பட்டியல்கள்',
    myShop: 'என் கடை',
    orders: 'ஆர்டர்கள்',
    profile: 'சுயவிவரம்',
    searchPlaceholder: 'விதைகள், நாற்றுகள் தேடவும்...',
    nearYou: 'உங்களுக்கு அருகில் கிடைக்கும்',
    trusted: 'நம்பகமான விற்பனையாளர்கள்',
    viewDetails: 'விவரம் காண்க',
    call: 'அழைக்கவும்',
    chat: 'அரட்டை அடிக்கவும்',
    transport: 'போக்குவரத்து வேண்டுமா?',
    addInventory: 'விற்கவும்',
    publish: 'பதிப்பிக்கவும்',
    variety: 'இனம்',
    quantity: 'அளவு',
    price: 'விலை',
    age: 'வயது',
    location: 'தற்போதைய இடம்',
    noOrders: 'ஆர்டர்கள் இல்லை',
    noOrdersDesc: 'உங்கள் சமீபத்திய கொள்முதல் மற்றும் விற்பனை இங்கே காட்டப்படும்.',
    startShopping: 'சந்தையை பாருங்கள்',
    unitsLabel: 'நகம்',
    verifiedChoice: 'சரிபார்க்கப்பட்ட தேர்வு',
    itemDetails: 'பொருள் விவரம்',
    qualityVerified: 'தரம் சரிபார்க்கப்பட்டது',
    selfPickup: 'நேரில் எடுக்கவும்',
    requestTransport: 'போக்குவரத்து உதவி கோரவும்',
    messages: 'செய்திகள்',
    sendEnquiry: 'விசாரணை அனுப்பவும்',
    enquirySent: 'விசாரணை அனுப்பப்பட்டது!',
    listingLocation: 'இடம்',
    viewMap: 'வரைபடம் காண்க',
    comingSoon: 'விரைவில் வருகிறது',
    comingSoonDesc: 'போக்குவரத்து முன்பதிவு விரைவில் கிடைக்கும்.',
    sellerProfile: 'விற்பனையாளர் சுயவிவரம்',
    daysOnApp: 'App-ல் நாட்கள்',
    itemsSold: 'விற்கப்பட்ட பொருட்கள்',
    otherListings: 'மற்ற பட்டியல்கள்',
    contactSeller: 'விற்பனையாளரை தொடர்பு கொள்ளவும்',
    noMessages: 'செய்திகள் இல்லை',
    noMessagesDesc: 'உரையாடல் தொடங்க விசாரணை அனுப்பவும்.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `வணக்கம், Swaseva-ல் உங்கள் ${productName} (₹${price}/${unit}) பார்த்தேன். மேலும் விவரங்கள் தரவும்.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `வணக்கம், Swaseva-ல் உங்கள் ${productName} (₹${price}/${unit}) பார்த்தேன். மேலும் விவரங்கள் தரவும்.`,
  },
  bn: {
    home: 'বাজার',
    sell: 'বিক্রি করুন',
    listings: 'তালিকা',
    myShop: 'আমার দোকান',
    orders: 'অর্ডার',
    profile: 'প্রোফাইল',
    searchPlaceholder: 'বীজ, চারা খুঁজুন...',
    nearYou: 'আপনার কাছে পাওয়া যাচ্ছে',
    trusted: 'বিশ্বস্ত বিক্রেতা',
    viewDetails: 'বিস্তারিত দেখুন',
    call: 'ফোন করুন',
    chat: 'চ্যাট করুন',
    transport: 'পরিবহন দরকার?',
    addInventory: 'বিক্রি করুন',
    publish: 'প্রকাশ করুন',
    variety: 'জাত',
    quantity: 'পরিমাণ',
    price: 'মূল্য',
    age: 'বয়স',
    location: 'বর্তমান স্থান',
    noOrders: 'কোনো অর্ডার নেই',
    noOrdersDesc: 'আপনার সাম্প্রতিক কেনাকাটা এবং বিক্রয় এখানে দেখা যাবে।',
    startShopping: 'বাজার দেখুন',
    unitsLabel: 'নং',
    verifiedChoice: 'যাচাইকৃত পছন্দ',
    itemDetails: 'পণ্যের বিবরণ',
    qualityVerified: 'গুণমান যাচাই করা হয়েছে',
    selfPickup: 'নিজে তুলে নিন',
    requestTransport: 'পরিবহন সহায়তা চান',
    messages: 'বার্তা',
    sendEnquiry: 'অনুসন্ধান পাঠান',
    enquirySent: 'অনুসন্ধান পাঠানো হয়েছে!',
    listingLocation: 'স্থান',
    viewMap: 'মানচিত্র দেখুন',
    comingSoon: 'শীঘ্রই আসছে',
    comingSoonDesc: 'পরিবহন বুকিং শীঘ্রই উপলব্ধ হবে।',
    sellerProfile: 'বিক্রেতার প্রোফাইল',
    daysOnApp: 'App-এ দিন',
    itemsSold: 'বিক্রি হওয়া পণ্য',
    otherListings: 'অন্যান্য তালিকা',
    contactSeller: 'বিক্রেতার সাথে যোগাযোগ করুন',
    noMessages: 'কোনো বার্তা নেই',
    noMessagesDesc: 'কথোপকথন শুরু করতে অনুসন্ধান পাঠান।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `নমস্কার, Swaseva-তে আপনার ${productName} (₹${price}/${unit}) দেখলাম। দয়া করে আরো তথ্য দিন।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `নমস্কার, Swaseva-তে আপনার ${productName} (₹${price}/${unit}) দেখলাম। দয়া করে আরো তথ্য দিন।`,
  },
  or: {
    home: 'ବଜାର',
    sell: 'ବିକ୍ରି କରନ୍ତୁ',
    listings: 'ତାଲିକା',
    myShop: 'ମୋ ଦୋକାନ',
    orders: 'ଅର୍ଡର',
    profile: 'ପ୍ରୋଫାଇଲ',
    searchPlaceholder: 'ବୀଜ, ଚାରା ଖୋଜନ୍ତୁ...',
    nearYou: 'ଆପଣଙ୍କ ନିକଟରେ ଉପଲବ୍ଧ',
    trusted: 'ବିଶ୍ୱସ୍ତ ବିକ୍ରେତା',
    viewDetails: 'ବିବରଣ ଦେଖନ୍ତୁ',
    call: 'ଫୋନ୍ କରନ୍ତୁ',
    chat: 'ଚ୍ୟାଟ୍ କରନ୍ତୁ',
    transport: 'ପରିବହନ ଦରକାର?',
    addInventory: 'ବିକ୍ରି କରନ୍ତୁ',
    publish: 'ପ୍ରକାଶ କରନ୍ତୁ',
    variety: 'ଜାତ',
    quantity: 'ପରିମାଣ',
    price: 'ମୂଲ୍ୟ',
    age: 'ବୟସ',
    location: 'ବର୍ତ୍ତମାନ ସ୍ଥାନ',
    noOrders: 'କୌଣସି ଅର୍ଡର ନାହିଁ',
    noOrdersDesc: 'ଆପଣଙ୍କ ସାମ୍ପ୍ରତିକ କ୍ରୟ ଏବଂ ବିକ୍ରୟ ଏଠାରେ ଦେଖାଯିବ।',
    startShopping: 'ବଜାର ଦେଖନ୍ତୁ',
    unitsLabel: 'ନଗ',
    verifiedChoice: 'ଯାଞ୍ଚ ହୋଇଥିବା ବିକଳ୍ପ',
    itemDetails: 'ଜିନିଷ ବିବରଣ',
    qualityVerified: 'ଗୁଣବତ୍ତା ଯାଞ୍ଚ',
    selfPickup: 'ନିଜେ ନିଅନ୍ତୁ',
    requestTransport: 'ପରିବହନ ସହାୟତା ଚାହୁଁଛନ୍ତି',
    messages: 'ବାର୍ତ୍ତା',
    sendEnquiry: 'ଅନୁସନ୍ଧାନ ପଠାନ୍ତୁ',
    enquirySent: 'ଅନୁସନ୍ଧାନ ପଠାଯାଇଛି!',
    listingLocation: 'ସ୍ଥାନ',
    viewMap: 'ମ୍ୟାପ୍ ଦେଖନ୍ତୁ',
    comingSoon: 'ଶୀଘ୍ର ଆସୁଛି',
    comingSoonDesc: 'ପରିବହନ ବୁକିଂ ଶୀଘ୍ର ଉପଲବ୍ଧ ହେବ।',
    sellerProfile: 'ବିକ୍ରେତା ପ୍ରୋଫାଇଲ',
    daysOnApp: 'App ରେ ଦିନ',
    itemsSold: 'ବିକ୍ରି ହୋଇଥିବା ଜିନିଷ',
    otherListings: 'ଅନ୍ୟ ତାଲିକା',
    contactSeller: 'ବିକ୍ରେତାଙ୍କ ସହ ଯୋଗାଯୋଗ',
    noMessages: 'କୌଣସି ବାର୍ତ୍ତା ନାହିଁ',
    noMessagesDesc: 'ବାର୍ତ୍ତାଳାପ ଆରମ୍ଭ କରିବାକୁ ଅନୁସନ୍ଧାନ ପଠାନ୍ତୁ।',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `ନମସ୍କାର, Swaseva ରେ ଆପଣଙ୍କ ${productName} (₹${price}/${unit}) ଦେଖିଲି। ଦୟାକରି ଅଧିକ ତଥ୍ୟ ଦିଅନ୍ତୁ।`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `ନମସ୍କାର, Swaseva ରେ ଆପଣଙ୍କ ${productName} (₹${price}/${unit}) ଦେଖିଲି। ଦୟାକରି ଅଧିକ ତଥ୍ୟ ଦିଅନ୍ତୁ।`,
  },
  ml: {
    home: 'മാർക്കറ്റ്',
    sell: 'വിൽക്കുക',
    listings: 'ലിസ്റ്റിംഗ്',
    myShop: 'എന്റെ കട',
    orders: 'ഓർഡറുകൾ',
    profile: 'പ്രൊഫൈൽ',
    searchPlaceholder: 'വിത്തുകൾ, തൈകൾ തിരയുക...',
    nearYou: 'നിങ്ങൾക്ക് അടുത്ത് ലഭ്യം',
    trusted: 'വിശ്വസനീയ വിൽപ്പനക്കാർ',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    call: 'വിളിക്കുക',
    chat: 'ചാറ്റ് ചെയ്യുക',
    transport: 'ഗതാഗതം വേണോ?',
    addInventory: 'വിൽക്കുക',
    publish: 'പ്രസിദ്ധീകരിക്കുക',
    variety: 'ഇനം',
    quantity: 'അളവ്',
    price: 'വില',
    age: 'പ്രായം',
    location: 'നിലവിലെ സ്ഥലം',
    noOrders: 'ഓർഡറുകൾ ഇല്ല',
    noOrdersDesc: 'നിങ്ങളുടെ സമീപകാല വാങ്ങലുകളും വിൽപ്പനകളും ഇവിടെ കാണിക്കും.',
    startShopping: 'മാർക്കറ്റ് കാണുക',
    unitsLabel: 'നഗ',
    verifiedChoice: 'സ്ഥിരീകരിച്ച തിരഞ്ഞെടുപ്പ്',
    itemDetails: 'ഇനം വിശദാംശം',
    qualityVerified: 'ഗുണനിലവാരം സ്ഥിരീകരിച്ചു',
    selfPickup: 'നേരിട്ട് എടുക്കുക',
    requestTransport: 'ഗതാഗത സഹായം ആവശ്യപ്പെടുക',
    messages: 'സന്ദേശങ്ങൾ',
    sendEnquiry: 'അന്വേഷണം അയക്കുക',
    enquirySent: 'അന്വേഷണം അയച്ചു!',
    listingLocation: 'സ്ഥലം',
    viewMap: 'ഭൂപടം കാണുക',
    comingSoon: 'ഉടൻ വരുന്നു',
    comingSoonDesc: 'ഗതാഗത ബുക്കിംഗ് ഉടൻ ലഭ്യമാകും.',
    sellerProfile: 'വിൽപ്പനക്കാരൻ പ്രൊഫൈൽ',
    daysOnApp: 'App-ൽ ദിവസങ്ങൾ',
    itemsSold: 'വിറ്റ ഇനങ്ങൾ',
    otherListings: 'മറ്റ് ലിസ്റ്റിംഗ്',
    contactSeller: 'വിൽപ്പനക്കാരനെ ബന്ധപ്പെടുക',
    noMessages: 'സന്ദേശങ്ങൾ ഇല്ല',
    noMessagesDesc: 'സംഭാഷണം ആരംഭിക്കാൻ അന്വേഷണം അയക്കുക.',
    enquiryAutoMsg: (productName: string, price: number, unit: string) =>
      `നമസ്കാരം, Swaseva-ൽ നിങ്ങളുടെ ${productName} (₹${price}/${unit}) കണ്ടു. കൂടുതൽ വിവരങ്ങൾ ദയവായി അറിയിക്കൂ.`,
    enquiryAutoMsgMr: (productName: string, price: number, unit: string) =>
      `നമസ്കാരം, Swaseva-ൽ നിങ്ങളുടെ ${productName} (₹${price}/${unit}) കണ്ടു. കൂടുതൽ വിവരങ്ങൾ ദയവായി അറിയിക്കൂ.`,
  },
};

export function getTranslations(lang: Language): typeof TRANSLATIONS.en {
  return (TRANSLATIONS as Record<string, typeof TRANSLATIONS.en>)[lang as string] ?? TRANSLATIONS.en;
}

export const PRICE_UNITS = [
  { value: 'kg',      label: 'per kg',      labelMr: 'प्रति किलो'      },
  { value: 'gram',    label: 'per 100g',    labelMr: 'प्रति १०० ग्रॅम'  },
  { value: 'quintal', label: 'per quintal', labelMr: 'प्रति क्विंटल'    },
  { value: 'tonne',   label: 'per tonne',   labelMr: 'प्रति टन'         },
  { value: 'dozen',   label: 'per dozen',   labelMr: 'प्रति डझन'        },
  { value: 'piece',   label: 'per piece',   labelMr: 'प्रति नग'         },
  { value: 'litre',   label: 'per litre',   labelMr: 'प्रति लिटर'       },
  { value: 'bundle',  label: 'per bundle',  labelMr: 'प्रति जुडी'       },
  { value: 'bag',     label: 'per bag',     labelMr: 'प्रति बोरे'       },
  { value: 'box',     label: 'per box',     labelMr: 'प्रति पेटी'       },
  { value: 'packet',  label: 'per packet',  labelMr: 'प्रति पॅकेट'      },
];

export const MOCK_SHOP_PROFILES: (ShopProfile & { shopkeeperId: string; shopNameMr: string; location: string; distance: string })[] = [
  {
    shopkeeperId: 'shop_001',
    shopName: 'Ganesh Krishi Seva Kendra',
    shopNameMr: 'गणेश कृषी सेवा केंद्र',
    location: 'Pune, Maharashtra',
    distance: '0.3 km',
    exteriorPhotoUri: 'https://images.unsplash.com/photo-1604719312566-8912e9c8a213?w=400',
    interiorPhotoUri: '',
    verificationStatus: 'pending' as const,
    gstOrLicense: 'GSTIN27AAACG1234A1ZD',
  },
  {
    shopkeeperId: 'shop_002',
    shopName: 'Shivaji Agro Stores',
    shopNameMr: 'शिवाजी अॅग्रो स्टोर्स',
    location: 'Nashik, Maharashtra',
    distance: '1.1 km',
    exteriorPhotoUri: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400',
    interiorPhotoUri: '',
    verificationStatus: 'pending' as const,
    gstOrLicense: 'LIC-PES-MH-2023-00142',
  },
  {
    shopkeeperId: 'shop_003',
    shopName: 'Mahalaxmi Seed House',
    shopNameMr: 'महालक्ष्मी सीड हाऊस',
    location: 'Aurangabad, Maharashtra',
    distance: '2.4 km',
    exteriorPhotoUri: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400',
    interiorPhotoUri: '',
    verificationStatus: 'pending' as const,
    gstOrLicense: 'GSTIN27BBBCM5678B2ZE',
  },
];

export const MOCK_SHOP_ITEMS: ShopItem[] = [
  { id: 'si_001', shopkeeperId: 'shop_001', name: 'Hybrid Tomato Seeds', nameMr: 'हायब्रिड टोमॅटो बियाणे', category: 'seeds', price: 280, unit: 'packet', stockQty: 45, stockThreshold: 10, description: '50g packet, disease resistant variety', descriptionMr: '50 ग्रॅम पॅकेट, रोगप्रतिकारक जात', imageUris: ['https://images.unsplash.com/photo-1592925741908-3c60d3a4a8c3?w=400'], brand: 'Syngenta', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_002', shopkeeperId: 'shop_001', name: 'NPK Fertilizer 19:19:19', nameMr: 'NPK खत 19:19:19', category: 'fertilizer', price: 1150, unit: 'bag', stockQty: 8, stockThreshold: 5, description: 'Water soluble complex fertilizer', descriptionMr: 'पाण्यात विरघळणारे संयुक्त खत', imageUris: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'], brand: 'Iffco', expiryDate: '2027-03-31', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_003', shopkeeperId: 'shop_002', name: 'Chlorpyrifos 20% EC', nameMr: 'क्लोरपायरीफॉस 20% EC', category: 'pesticide', price: 420, unit: 'litre', stockQty: 3, stockThreshold: 5, description: 'Broad spectrum insecticide', descriptionMr: 'व्यापक स्पेक्ट्रम कीटकनाशक', imageUris: ['https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=400'], brand: 'Coromandel', expiryDate: '2026-12-31', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_004', shopkeeperId: 'shop_002', name: 'Hand Sprayer 16L', nameMr: 'हँड स्प्रेयर 16L', category: 'tools', price: 1850, unit: 'piece', stockQty: 12, stockThreshold: 3, description: 'Knapsack pressure sprayer', descriptionMr: 'नॅपसॅक प्रेशर स्प्रेयर', imageUris: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400'], isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_005', shopkeeperId: 'shop_003', name: 'Cotton Seed BG-II', nameMr: 'कापूस बियाणे BG-II', category: 'seeds', price: 920, unit: 'packet', stockQty: 30, stockThreshold: 8, description: 'Bt cotton high yield variety', descriptionMr: 'बीटी कापूस उच्च उत्पादन जात', imageUris: ['https://images.unsplash.com/photo-1573848933048-bba9a57b5bca?w=400'], brand: 'Mahyco', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
  { id: 'si_006', shopkeeperId: 'shop_003', name: 'Animal Feed Pellets', nameMr: 'पशुखाद्य गोळ्या', category: 'feed', price: 650, unit: 'bag', stockQty: 20, stockThreshold: 5, description: 'Balanced nutrition cattle feed', descriptionMr: 'संतुलित पोषण गोमांस खाद्य', imageUris: ['https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=400'], brand: 'Godrej Agrovet', isActive: true, createdAt: '2026-04-01T00:00:00Z' },
];
